---
title: "Establishing relationships between LWC and MPa"
author: "Indra Boving"
date: "11/8/2022"
output: html_document
---

##setup
```{r setup, include=FALSE}
#install.packages("MuMIn")
#devtools::install_github("an-bui/calecopal")

library(data.table)
library(janitor)
library(here)
library(tidyverse)
library(lubridate)
library(readxl)
library(gridExtra)
library(calecopal)
library(rstatix)
library(vars)
library(MuMIn)
library(lme4) #for mixed effects models
library(cowplot)

select = dplyr::select

library('variancePartition')


source(here::here("scripts", "scripts_functions", "plotPercentBars_IB.R"))

source(here::here("scripts", "scripts_functions", "figure_info.R"))



# datver <- "20230220"
# dataversion <- paste0("Data_", datver)
```


```{r}
wc_all_raw <- read_csv(here("processed-data", paste0("wp_wc_rwc_",datver,".csv")), show_col_types = F) %>%   #mutate(lwc_mean = lwc_mean_combined) %>% 
  filter(lwc_mean > 0, 
         lwc_mean < 3)
```

Before leafout: 

```{r}
qudo_wc_all <- wc_all_raw %>% 
  filter( #week > 15, 
         species == "blue oak", 
         lwc_mean < 10) %>% 
  group_by(tree, week, time, lwc_mean) %>% 
  mutate(water_potential = mean(mpa_mean), 
         lwc = lwc_mean, 
         week_fact = as.factor(week), 
         tree_fact = as.factor(tree))
```

```{r}
form  <- ~ mpa_mean + (1|week_fact) + (1|tree_fact)  + (1|site)
lfm_matrix <- qudo_wc_all %>% 
  ungroup() %>% 
  mutate(id = row_number()) %>% 
  select(id, lwc_mean) %>% 
  pivot_wider(names_from = id, 
              values_from = lwc_mean) 

varPart <- fitExtractVarPartModel(lfm_matrix, form, qudo_wc_all )
varPart

all_vdc <- plotPercentBars.new(varPart)+
  labs(title = "All weeks")
all_vdc
```
```{r}
qudo_wc_lin <- qudo_wc_all %>% 
  filter(week > 15)

form  <- ~ mpa_mean + (1|week_fact) + (1|tree_fact)  + (1|plot)

lfm_matrix <- qudo_wc_lin %>% 
  ungroup() %>% 
  mutate(id = row_number()) %>% 
  select(id, lwc_mean) %>% 
  pivot_wider(names_from = id, 
              values_from = lwc_mean) 

varPart <- fitExtractVarPartModel(lfm_matrix, form, qudo_wc_lin )
varPart

lin_vdc <- plotPercentBars.new(varPart)
lin_vdc
```

```{r}
qudo_wc_lin <- qudo_wc_all %>% 
  filter(week > 19)

form  <- ~ mpa_mean + (1|week_fact) + (1|tree_fact)  + (1|site)

lfm_matrix <- qudo_wc_lin %>% 
  ungroup() %>% 
  mutate(id = row_number()) %>% 
  select(id, lwc_mean) %>% 
  pivot_wider(names_from = id, 
              values_from = lwc_mean) 

varPart <- fitExtractVarPartModel(lfm_matrix, form, qudo_wc_lin )
varPart

lin_vdc <- plotPercentBars.new(varPart) +
  labs(title = "After week 17")
lin_vdc
```

Put together: 
```{r}
cowplot::plot_grid(lin_vdc, all_vdc)
```

Mpa from LWC: 

```{r}
form  <- ~ lwc_mean + (1|week_fact) + (1|tree_fact)  + (1|site)

lfm_matrix <- qudo_wc_all %>% 
  drop_na(mpa_mean, lwc_mean) %>% 
  ungroup() %>% 
  mutate(id = row_number()) %>% 
  select(id, mpa_mean) %>% 
  pivot_wider(names_from = id, 
              values_from = mpa_mean) 

varPart <- fitExtractVarPartModel(lfm_matrix, form, qudo_wc_all )
varPart

all_vdc <- plotPercentBars.new(varPart)+
  labs(title = "All weeks")
all_vdc
```
```{r}
qudo_wc_lin <- qudo_wc_all %>% 
  filter(week > 15)

form  <- ~ lwc_mean + (1|week_fact) + (1|tree_fact)  + (1|plot)

lfm_matrix <- qudo_wc_lin %>% 
  ungroup() %>% 
  mutate(id = row_number()) %>% 
  select(id, mpa_mean) %>% 
  pivot_wider(names_from = id, 
              values_from = mpa_mean) 

varPart <- fitExtractVarPartModel(lfm_matrix, form, qudo_wc_lin )
varPart

lin_vdc <- plotPercentBars.new(varPart)
lin_vdc
```

```{r}
qudo_wc_lin <- qudo_wc_all %>% 
  filter(week > 19)

form  <- ~ lwc_mean + (1|week_fact) + (1|tree_fact)  + (1|site)

lfm_matrix <- qudo_wc_lin %>% 
  ungroup() %>% 
  mutate(id = row_number()) %>% 
  select(id, mpa_mean) %>% 
  pivot_wider(names_from = id, 
              values_from = mpa_mean) 

varPart <- fitExtractVarPartModel(lfm_matrix, form, qudo_wc_lin )
varPart

lin_vdc <- plotPercentBars.new(varPart) +
  labs(title = "After week 17")
lin_vdc
```

Put together: 
```{r}
cowplot::plot_grid(lin_vdc, all_vdc)
```
