
```{r}
library(cowplot)
library(grid)
library(gridExtra)
```

#DATA
```{r}
data_og <- read_csv(here("processed-data", paste0("cwc_analysis",datver,".csv")), show_col_types = F) %>%  
  filter(species %in% c("blue oak")) %>% 
  select(tree, week, water_potential, cwc, time_season, time) %>% 
  distinct() 
```

```{r}
final_df_all <- read_csv(here::here("processed-data", "bootstrapped_df_cwc.csv")) 
```



#####Space - faceted

```{r}
#scaled
space_nice_2 <- data_og %>% 
  filter(time == "md", 
         week %in% c(14, 19, 20, 37)) %>% 
  select(tree, week, water_potential, cwc) %>% 
  distinct() %>% 
  drop_na(cwc, water_potential) %>% 
  ggplot(aes(y = water_potential, 
            x = cwc,
             color = as.factor(week)
             )) +
  geom_point(alpha = .5, 
            # aes (shape = site)
             ) +
  theme(legend.position="top",
       # legend.position= c(.7, .2),
      strip.background = element_blank(),
      strip.text.x = element_text(size = 12),
      plot.title = element_text(size=13),
     # axis.title = element_text(size = 16),
     axis.text.y = element_text(size = 12),
     axis.text.x = element_text(size = 12),
    # axis.text.x  = element_blank(),
    # legend.key=element_blank(), 
    #  axis.title.x = element_blank(),
   #  axis.title.y = element_blank(),
     legend.text = element_text(size = 13), 
     legend.title = element_text(size = 16),
     legend.margin=margin(0,0,0,0),
      legend.box.margin=margin(-5,-8,-8,-8)
    ) +
  geom_smooth(method = "lm", se = F,size = .5) + 
 # geom_vline(xintercept = 0, linetype = "dotted") +
  labs(#y= "Middays (MPa)", 
       y = "Middays (MPa)",
       x = "CWC (g/cm2)", 
       color = "Week", 
       shape = "Site") +
  #color_many_2 +
  color_week_assigned +
  guides(color = guide_legend(nrow = 1)) +
  facet_wrap(~week, nrow = 1)+
  #scale_x_reverse() +
scale_y_continuous(labels = scales::number_format(accuracy = 0.1))
space_nice_2

```

#Slopes: 

####Space

```{r}
space_slope <-  final_df_all %>% 
   filter(!week %in% c(9)) %>% 
  filter(analysis == "space") %>% 
 # mutate(week = as.numeric(week)) %>% 
   ggplot(aes(color= as.factor(week))
    ) + 
  geom_point(aes(y = slope ,x = as.factor(week)), size =2) +
    geom_point(aes(y = upr, x = as.factor(week)), size = 1) +
  geom_point(aes(y = lwr, x = as.factor(week)), size = 1) +
  #geom_line(aes(group = week, y = week, x = upr)) +
  geom_segment(aes(y= lwr, 
                   yend = upr, 
                   x = as.factor(week), 
                   xend = as.factor(week), 
                   color = as.factor(week)))+
  labs(x = "Week", 
       color = "Week", 
       y = " ") +
  theme(legend.position="none",
       # legend.position= c(.7, .2),
      strip.background = element_blank(),
      strip.text.x = element_text(size = 12),
      plot.title = element_text(size=13),
     # axis.title = element_text(size = 16),
     axis.text.y = element_text(size = 12),
     axis.text.x = element_text(size = 12),
    # axis.text.x  = element_blank(),
     legend.key=element_blank(), 
      axis.title.x = element_blank(),
     axis.title.y = element_blank(),
     legend.text = element_text(size = 13), 
     legend.title = element_text(size = 16),
     legend.margin=margin(0,0,0,0),
      legend.box.margin=margin(-5,-8,-8,-8),
    plot.margin = unit(c(5.5, 5.5, 0, 5.5), units = "pt")
    ) +
  #scale_x_continuous(breaks = c(10, 12, 14,15, 17, 19, 21, 29, 33, 37)
                  #   breaks = c(37, 33, 29, 21, 19, 17, 15, 14, 12, 10)
                      # seq(10, 30, by = 1)
  #                   ) +
  geom_hline(yintercept = 0, linetype="dotted") + 
  color_week_assigned +
 # color_many_2 +
  guides(color = guide_legend(nrow = 2))
 # scale_x_reverse()
space_slope

unique(cwc_analysis_df$week_cwc_link)
unique(cwc_analysis_df$date_wp)
```


SE: 

```{r, eval = F}
# space_slope <- ran_df_week_4 %>% 
#   mutate(week = as.numeric(week)) %>% 
#  # filter(week %in% c(14, 17, 21, 29)) %>% 
#  # filter(term == "cwc") %>% 
#   mutate(upr = slope + (std.error.slope), 
#          lwr = slope - (std.error.slope)) %>% 
#   ggplot(aes(color= week)
#     ) + 
#   geom_point(aes(y = slope ,x = week), size =2) +
#     geom_point(aes(y = upr, x = week), size = 1) +
#   geom_point(aes(y = lwr, x = week), size = 1) +
#   #geom_line(aes(group = week, y = week, x = upr)) +
#   geom_segment(aes(y= lwr, 
#                    yend = upr, 
#                    x = week, 
#                    xend = week, 
#                    color = week))+
#   labs(x = "Week", 
#        color = "Week", 
#        y = " ") +
#   theme(legend.position="none",
#       strip.background = element_blank(),
#       strip.text.x = element_text(size = 12),
#       plot.title = element_text(size=13),
#       axis.title.y = element_text(size = 15),
#       axis.title.x = element_blank(),
#      axis.text = element_text(size = 12),
#      legend.key=element_blank(), 
#      legend.text = element_text(size = 13), 
#     # legend.title = element_text(size = 16),
#     legend.title = element_blank(),
#      legend.margin=margin(0,0,0,0),
#       legend.box.margin=margin(-5,-8,-8,-8)
#     ) +
#   scale_x_continuous(breaks = c(10, 12, 14,15, 17, 19, 21, 29, 33, 37)
#                   #   breaks = c(37, 33, 29, 21, 19, 17, 15, 14, 12, 10)
#                       # seq(10, 30, by = 1)
#                      ) +
#   geom_hline(yintercept = 0, linetype="dotted") + 
#   color_grad_new +
#  # color_many_2 +
#   guides(color = guide_legend(nrow = 2)) 
# space_slope
```
####Time

BS:

```{r}
time_summary <- final_df_all %>% 
   filter(!week %in% c(9)) %>% 
  filter(analysis == "time, ind. tree") %>% 
   mutate(week = as.factor(week), 
          time_season = case_when(
            time_season %in% c("before leafout") ~ "During", 
             time_season %in% c("after leafout") ~ "After", 
            
          )) %>% 
ggplot(aes(color = time_season)) + 
  geom_point(aes(y = slope, x = time_season), size =3) +
  geom_point(aes(y = upr, x = time_season), size = 1) +
  geom_point(aes(y = lwr, x = time_season), size = 1) +
  geom_segment(aes(y= lwr, 
                   yend = upr, 
                   x = time_season, 
                   xend = time_season)) +
  labs(y = "",
       x = "Time") +
  color_two_grey +
  geom_hline(yintercept = 0, linetype="dotted") + 
  theme(legend.position="none",
       # legend.position= c(.7, .2),
      strip.background = element_blank(),
      strip.text.x = element_text(size = 12),
      plot.title = element_text(size=13),
     # axis.title = element_text(size = 16),
     axis.text.y = element_text(size = 12),
     axis.text.x = element_text(size = 12),
    # axis.text.x  = element_blank(),
     legend.key=element_blank(), 
      axis.title.x = element_blank(),
     axis.title.y = element_blank(),
     legend.text = element_text(size = 13), 
     legend.title = element_text(size = 16),
     legend.margin=margin(0,0,0,0),
      legend.box.margin=margin(-5,-8,-8,-8),
    plot.margin = unit(c(5.5, 5.5, 0, 5.5), units = "pt")
    ) +
  scale_x_discrete(limit = rev)
  
time_summary
```





#*FIGURES*


#Scatterplots:

#####Space

```{r}
#scaled
space_nice_1 <- data_og %>% 
  filter(time == "md") %>% 
  select(tree, week, water_potential, cwc) %>% 
  distinct() %>% 
  drop_na(cwc, water_potential) %>% 
  ggplot(aes(y = water_potential, 
            x = cwc,
             color = as.factor(week)
             )) +
  geom_point(alpha = .5, 
            # aes (shape = site)
             ) +
  theme(legend.position="none",
       # legend.position= c(.7, .2),
      strip.background = element_blank(),
      strip.text.x = element_text(size = 12),
      plot.title = element_text(size=13),
     # axis.title = element_text(size = 16),
     axis.text.y = element_text(size = 12),
     axis.text.x = element_text(size = 12),
    # axis.text.x  = element_blank(),
     legend.key=element_blank(), 
      axis.title.x = element_blank(),
     axis.title.y = element_blank(),
     legend.text = element_text(size = 13), 
     legend.title = element_text(size = 16),
     legend.margin=margin(0,0,0,0),
      legend.box.margin=margin(-5,-8,-8,-8),
    plot.margin = unit(c(5.5, 5.5, 0, 5.5), units = "pt")
    ) +
  geom_smooth(method = "lm", se = F,size = .5) + 
 # geom_vline(xintercept = 0, linetype = "dotted") +
  labs(#y= "Middays (MPa)", 
       y = " ",
       x = "Leaf Water per Area", 
       color = "Week", 
       shape = "Site") +
  #color_many_2 +
  color_week_assigned +
 # xlim(.5,2) +
 # ylim(-5,0)+
  guides(color = guide_legend(nrow = 2)) +
  #scale_x_reverse() +
scale_y_continuous(labels = scales::number_format(accuracy = 0.1))
space_nice_1


```
#####Time:

```{r}
time_1 <- data_og %>% 
  mutate(time = case_when(
    time == "md" ~ "Midday", 
    time == "pd" ~ "Predawn"
  )) %>% 
  filter(time == "Midday") %>% 
  drop_na(week) %>% 
 # filter(time == "md") %>% 
  ggplot(aes(y = water_potential, 
             x = cwc, 
             color = time_season, 
             size = week,
             shape = as.factor(tree),
             show.legend = FALSE)) +
  geom_point(size = 1,
             alpha = .1)+
  geom_smooth(method = "lm", se = F, size = .5, alpha = .4) +
 # theme(legend.position = "none") +
  labs(x = "lwc_mean", 
       y = "Midday MPa") +
  #color_two_grey +
  theme(
      legend.position="none",
      strip.background = element_blank(),
     # strip.text.x = element_text(size = 12),
      strip.text.x = element_text(size = 12),
      plot.title = element_text(size=13),
      #axis.title = element_text(size = 15),
     axis.title = element_blank(),
     axis.text = element_text(size = 12),
     axis.text.x = element_text(size = 12),
     legend.key=element_blank(),
     legend.text = element_text(size = 13),
     legend.title = element_text(size = 16),
     #legend.title = element_blank(),
     legend.margin=margin(0,0,0,0),
      legend.box.margin=margin(-5,-8,-8,-8),
     plot.margin = unit(c(5.5, 5.5, 0, 5.5), units = "pt")
    ) +
  labs(#y= "Water Potential (MPa)", 
       y = "Water Potential (MPa)",
       x = "Leaf Water Content (g)", 
       color = "Week", 
       ) +
  guides(color = guide_legend(nrow = 2)) +
  color_two_grey +
scale_y_continuous(labels = scales::number_format(accuracy = 0.1))

time_1 
```

######Legend:

```{r}
legend_plot <- data_og %>% 
  mutate(time = case_when(
    time == "md" ~ "Midday", 
    time == "pd" ~ "Predawn"
  )) %>% 
  filter(time == "Midday") %>% 
  drop_na(week) %>% 
  ggplot(aes(y = water_potential,
             x = cwc,
             color = as.factor(week), 
            # shape = as.factor(time),
             )) +
  geom_point() +
  theme(legend.position="top",
       # legend.position= c(.7, .2),
      strip.background = element_blank(),
      strip.text.x = element_text(size = 12),
      plot.title = element_text(size=13),
     # axis.title = element_text(size = 16),
     axis.text = element_text(size = 12),
     legend.key=element_blank(), 
     axis.title.x = element_blank(),
     axis.title.y = element_blank(),
     legend.text = element_text(size = 13), 
     legend.title = element_text(size = 16),
     legend.margin=margin(0,0,0,0),
    legend.box.margin=margin(-5,-8,-8,-8)
    ) +
  geom_smooth(method = "lm", se = F, size = .5) + 
  labs(color = "Week", 
       shape = "Time") +
  color_week_assigned +
 # ylim(0,2) +
  guides(color = guide_legend(nrow = 2))
legend_plot

legend_scatterplots <- cowplot::get_legend(legend_plot)
legend_scatterplots
```

#COMBINE

```{r}
library(grid)
#labels of slopes: 
y.grob1 <- textGrob("Slope", 
                   gp=gpar(fontface="bold", #col="blue", 
                           fontsize=15), rot=90)

x.grob1 <- textGrob("Time", 
                   gp=gpar(fontface="bold", #col="blue", 
                           fontsize=15))

combined_slopes_wide <- cowplot::plot_grid(space_slope, NULL, time_summary,
                                           # NULL, pv_slope,
                                   nrow = 1, 
                                  rel_widths = c(1, -.005, 1  #, -.02, .5
                                                 ), 
                                  labels = c("B", "", "D"#,"", "G"
                                             ),
                                  label_x = .1,
                                  #hjust= c(3, 0, 3),
                                  label_y = .98
                                  # rel_heights = c(.15, 1, .3), 
                                   #rel_widths = c(1, 1, 1), 
                                  # rel_widths = c(.7, .8, .7, .3)
                                   ) 

combined_slopes_wide

combined_slopes_wide_labels <- grid.arrange(arrangeGrob(combined_slopes_wide, 
                            left = y.grob1, 
                            bottom = x.grob1),
                            heights = c(1, .05))

#labels of scatterplots: 
y.grob2 <- textGrob("Water Potential (MPa)", 
                   gp=gpar(fontface="bold", #col="blue", 
                           fontsize=15), rot=90)

x.grob2 <- textGrob("Canopy Water Content (g/cm2)", 
                   gp=gpar(fontface="bold", #col="blue",
                           fontsize=15))


combined_plots_wide_nolegend <- cowplot::plot_grid(space_nice_1, NULL, 
                                      time_1,
                                   labels=c("A","", "C"),
                                   label_x = .1,
                                   label_y = .98,
                                   nrow = 1,
                                   rel_widths = c(1, -0, 1)
                                   #rel_widths = c(1, 1, 1)
                                   ) 
combined_plots_wide_nolegend

combined_plots_wide <- cowplot::plot_grid(legend_scatterplots,
                                      combined_plots_wide_nolegend,
                                          nrow = 2, 
                                          rel_heights = c(.2, 1))

combined_plots_wide_labels <- grid.arrange(arrangeGrob(combined_plots_wide, 
                                left = y.grob2, 
                                bottom = x.grob2,
                                heights = c(1, 0)))

combined_plots_all <- cowplot::plot_grid(
  combined_plots_wide_labels, 
  combined_slopes_wide_labels, 
          nrow = 2, 
          rel_heights = c(.75, .6))

combined_plots_all

ggsave(here("figures", "qudo figures", "CWC", "combined_plots_all_qudo"), combined_plots_all, device = "jpg", width = 8, height = 7, dpi = 300)
```
