---
title: "Maps"
author: "Indra Boving"
date: "02/15/2023"
output: html_document
---

##setup


```{r setup, include=FALSE}
#install.packages("rstatix")
#devtools::install_github("an-bui/calecopal")
#install.packages("tidyverse")
library(here)
library(sf)
library(raster)
library(paletteer) 
library(RColorBrewer)

# some namespace issue with raster and some of these packages.
#library(dplyr)
library(tidyverse)
library(readxl)
library(car)
library(lubridate)
library(ggmap)
library(janitor)

select = dplyr::select
 
#source("http://goo.gl/UUyEzD") #outlier KD (original function)

source(here::here("scripts","scripts_functions", "figure_info.R"))
```

#Data
```{r}
# datver <- "07192022"
# dataversion <- paste0("Data_", datver)

### Processed water potentials (individual measurements)

# Indra's version
wp_alldates <- read.csv(here("processed-data", paste0("wp_alldates_",datver,".csv")))
# lee's version
wp_ad <- read.csv(here("processed-data", paste0("wp_alldates_long_",datver,".csv")))[,-1]
wp_ad$tag <- str_replace(wp_ad$tag, "\\.0","") # get rid of annoying .0 at end of numeric tags (thanks excel)

## table for linking tree numbers with sites, correct some mislabeling
treesite <- read_excel(here(dataversion,"WP_WC","SHIFT data collection 2022.xlsx"),sheet="Tree_Sites", skip=0, na = "NA", col_types = "text")
treesite$Tag <- str_replace(treesite$Tag, "\\.0","")


wp_ad$plot <- treesite$Plot[match(wp_ad$tag, treesite$Tag)]
```

```{r}
###### Sedgwick DEM
sdem <- raster::raster(here("Data_05042022", "geospatial", "DEM_sedgwick_3m.tif"))
#sdemll <- st_transform(sdem, crs= 4326)
#sdemll <- raster::projectRaster(sdem)
# make a df for plotting with ggplot
sdem_gg <- sdem %>%
  rasterToPoints() %>%
  data.frame()

#### Tree Locations
latlon <- read.csv(here("Data_05042022", "Trees_LatLon_v2.csv"))
colnames(latlon)[1:2] <- c("Longitude","Latitude")
# pull out 'B' and 'L' at start of tree names
latlon$Tree <- latlon$Name
latlon$Tree <- str_remove(pattern="B", string=latlon$Tree)
latlon$Tree <- str_remove(pattern="L", string=latlon$Tree)
# make this a seperate species column
latlon$Species <- NA
latlon$Species[grep("B",latlon$Name )] <- "B"
latlon$Species[grep("L",latlon$Name )] <- "L"
# fix shrub names
latlon$Species[grep("Art",latlon$Name)] <- "ARCA"
latlon$Species[grep("LE",latlon$Name)] <- "LEU"
latlon$Tree[which(latlon$Species=="ARCA")] <- c("Chamise-ARCA","Cucu-ARCA","LL-ARCA")
latlon$Tree[which(latlon$Species=="LEU")] <- c("Cucu-LEU","LL-LEU")
latlon$Tree[grep("Dont", latlon$Name)] <- "2373"

latlon <- latlon %>% 
  clean_names()

write_csv(latlon, here("processed-data", "geospatial", "trees_latlon.csv"))

# make a latlon and utm spatial data version
latlon.ll <- SpatialPointsDataFrame(coords = data.frame(latlon$longitude, latlon$latitude),
                                    proj4string = CRS("+proj=longlat +datum=WGS84"), 
                                    data=latlon)
latlon.ll
latlon.utm <- spTransform(latlon.ll, CRSobj = crs(sdem))

latlon.utm
```


```{r}
P50doug <- 4.43 # average of all of our wild curves from Skelton et al. 2019 NP
P50ag <- 4.32 # from Skelton et al. 2018 Plant Phys

############## END: Load Data ##################3
```

Data load, combine and clean: 

```{r}
#### Lee's version which hopefully cuts down on replicate values
wp_ind_long <- wp_ad %>% 
  group_by(tree, site, plot, species, week, date, time) %>% 
  summarise(sd.mpa = sd(mpa), mpa = mean(mpa)) %>% 
  mutate(tree = as.character(tree))

# rename midday and predawn columns so I can combine them
wp_ind_md <- wp_ind_long[wp_ind_long$time=="md",]
wp_ind_md <- wp_ind_md %>% rename(md_mpa = mpa, date_md=date, md_sd.mpa = sd.mpa)

wp_ind_pd <- wp_ind_long[wp_ind_long$time=="pd",]
wp_ind_pd <- wp_ind_pd %>% rename(pd_mpa = mpa, date_pd=date, pd_sd.mpa = sd.mpa)

wp_ind <- full_join(wp_ind_md %>% select(-time), wp_ind_pd %>% select(-time))
wp_ind <- left_join(wp_ind, latlon, by=c("tree"))


# calculate delta Psi
wp_ind$e_drop <- wp_ind$md_mpa-wp_ind$pd_mpa

# add in lat lon and utm
wp_ind$lat_utm <- latlon.utm@coords[match( wp_ind$tree,latlon.utm$tree),2]
wp_ind$lon_utm <- latlon.utm@coords[match( wp_ind$tree,latlon.utm$tree),1]

# make a spatialdata version, dropping trees without coords
wp_ind_utm <- SpatialPointsDataFrame(coords = data.frame(wp_ind$lon_utm[-which(is.na(wp_ind$lon_utm))], wp_ind$lat_utm[-which(is.na(wp_ind$lon_utm))]), proj4string = crs(sdem), data=wp_ind[-which(is.na(wp_ind$lon_utm)),])

#remove non-trees: 
wp_ind_new <- wp_ind %>% 
 # filter(!species %in% c("ARCA", "LEU")) %>% 
 # mutate(species = species_x) %>% 
  #select(-species_x, -species_y) %>% 
  drop_na(latitude, longitude)

write_csv(wp_ind_new, here("processed-data", "geospatial", "wp_ind_new.csv"))

### making a spatial dataframe
latlonproj <- CRS("+proj=longlat +datum=WGS84")

wp_ind.ll <- SpatialPoints(coords = data.frame(wp_ind_new$longitude, wp_ind_new$latitude), 
                           proj4string = latlonproj)
# aeaproj <- projection(sdem)
# aeaproj <- CRS("+proj=aea +lat_1=34.0 +lat_2=40.5 +lat_0=0.0 +lon_0=-120 +x_0=0 +y_0=-4000000")
wp.ind.aea <- sp::spTransform(wp_ind.ll,CRSobj =  crs(sdem))
wp.indsp <- SpatialPointsDataFrame(wp.ind.aea, wp_ind_new)
```



```{r}
##### Data Characterization:
length(which(is.na(wp_ind_new$e_drop)))
# half of our obs either don't have a pd or don't have a md
# only 191 of 385 obs have both

xtabs(~week, wp_ind_new)
# but at least I don't have more measurements than we have trees in any given week!
xtabs(~week, wp_ind_new[wp_ind_new$pd_mpa>0,])
  # Missing a lot of predawns from
# Week 15 (have 30 of 59)
# Week 18 (have 6 of 28)
# Week 19 (have 40 of 61)
# Week 21 (have 30 of 42)

xtabs(~week, wp_ind_new[wp_ind_new$md_mpa>0,])
# Missing a lot of middays from
# Week 11 (have 9 of 29)
# Week 13 (have 0 of 27)
# Week 21 (have 32 of 42)

wp_ind_new <- wp_ind_new %>% 
  mutate(species = species.x)

### Make a master list of trees:
alltrees <- wp_ind_new %>% 
  group_by(tree, site, plot, species) %>% 
  summarise(n_pds = length(which(pd_mpa >0)), n_mds = length(which(md_mpa>0)))

write.csv(alltrees, here("processed-data", paste0("FullTreeList_fromwps",datver,".csv")))

################ END: Data loading, combining, cleaning ##############3
```

########### DATA VIZ ##############

```{r}
### trying with ggplot
install.packages(c("cowplot", "googleway", "ggplot2", "ggrepel", 
"ggspatial", "libwgeom", "sf", "rnaturalearth", "rnaturalearthdata"))

ggplot() + 
  geom_raster(data=sdem_gg, aes(x=x, y=y, fill=DEM_sedgwick_3m)) + 
  xlim(LLBB[1,1:2]) + 
  ylim(LLBB[2,1:2])
class(sdem_gg)

wells_sf <- st_as_sf(sdem_gg, coords = c("x","y"),
                    # crs= "+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0"
                     crs= "+proj=longlat +datum=WGS84"
                     )

class(wells_sf)
wells_sf
```


```{r}
# Generate empty raster layer and rasterize points
raster <- raster(crs = crs(wells_sf), 
                 vals = 0, 
                 resolution = c(0.5, 0.5), 
                 ext = extent(c(-97.1268, -97.099334, 31.536245, 31.559652))) %>%
   rasterize(wells_sf, .)


ggplot() +
    #geom_sf(aes(fill=DEM_sedgwick_3m)) +
    geom_raster(data = sdem_gg, aes(x=x, y=y, fill = DEM_sedgwick_3m))+
 # geom_raster(data=sdem_gg, aes(x=x, y=y, fill=DEM_sedgwick_3m)) +
    ggspatial::annotation_scale(location = "bl", width_hint = 0.5) +
    ggspatial::annotation_north_arrow(location = "bl", which_north = "true", 
        pad_x = unit(0.75, "in"), pad_y = unit(0.5, "in"),
       # style = north_arrow_fancy_orienteering
        ) +
    coord_sf(xlim = c( -97.1268, -97.099334), ylim = c(31.536245, 31.559652))
```


```{r}
ggplot() +
  geom_raster(data = dem.df, aes(lon, lat, fill = alt), alpha = .45) +
  scale_fill_gradientn(colours = terrain.colors(100)) +
  geom_sf(data = my_bbox_buff_2500.sf, fill = NA) +
  coord_sf(xlim = c(st_bbox(my_bbox_buff_25000.sf)['xmin'], st_bbox(my_bbox_buff_25000.sf)['xmax']), 
           ylim = c(st_bbox(my_bbox_buff_25000.sf)['ymin'], st_bbox(my_bbox_buff_25000.sf)['ymax'])) +
  geom_polygon(data = my_world_map, 
               aes(x=long, y = lat, group = group), fill = NA, colour = 'black') +
  theme_bw()

```


```{r}
######### Failed mapping
# c(left = -97.1268, bottom = 31.536245, right = -97.099334, top = 31.559652))

# summary(wp_ind.ll)
# myMap <- get_map(location=c(left=-120.051, bottom=34.6853,right= - 120.0401, top=34.7187), source="google", maptype="terrain", zoom=12)
# 
# LLMap <-get_map(location=c(left=-120.0487, bottom=34.689,right= - 120.0455, top=34.6925), source="google", maptype="terrain", zoom=14)
```


```{r}
### all sedgewick, plotted in UTM
plot(sdem,ylim=bbox(latlon.utm)[2,1:2], xlim=bbox(latlon.utm)[1,1:2]) 
points(latlon.utm)
#ylim=c(34.689,34.6925), xlim=c(-120.049, -120.045)

# just LL
LLbb <- bbox(wp_ind_utm[which(wp_ind_utm$site=="LL"),])
LLBB <- cbind(LLbb[,1]-50, LLbb[,2]+50)
# crop dem to just lower lisque
demLL <- crop(sdem, LLBB)

plot(demLL, col=viridis::viridis(100))
```


```{r}
#-------------------------------------------------
#### Predawn LL Map Comparison #######
#quartz(width=8, height=5)
#par(mfrow=c(1,2))

###### predawn from April
#bluecol <- paste0(brewer.pal(n=3,"Set1")[2],"AA")
#livecol <- paste0(brewer.pal(n=3,"Set1")[1],"88")
bluecol <-paletteer_d("awtools::mpalette")[3]# brewer.pal(n=3,"Set1")[2]
livecol <- brewer.pal(n=3,"Set1")[1] # "#FFC107"
p50col <- "#FFC107" # paletteer_d("awtools::spalette")[6] 

plot(demLL, col= grey(1:150/150)[51:150], legend=F
     , main="April\n"
     , xaxt="n",yaxt="n"
     , ylab="")
mtext(side=2, "Soil Dryness", font=2, line=1.5, cex=1.2)
contour(demLL, add=T)
points(wp_ind_utm[which(wp_ind_utm$species=="blue oak" & wp_ind_utm$week==15),]
       , pch=21
       , cex=wp_ind_utm$pd_mpa[which(wp_ind_utm$species=="blue oak" & wp_ind_utm$week==15)]*.8
       , bg=bluecol)
points(wp_ind_utm[which(wp_ind_utm$species=="live oak" & wp_ind_utm$week==15),]
       , pch=21
       , cex=wp_ind_utm$pd_mpa[which(wp_ind_utm$species=="live oak" & wp_ind_utm$week==15)]*.8
       , bg=livecol)
par(xpd=NA)
arrows(x0=-4100, y0=-369450, y1=-369380, xpd=NA, lwd=2,length=.2 )
text("N", font=2, x=-4100, y=-369360, cex=1.8)
par(xpd=T)

legend(x=-4150, y=-369600, xpd=NA
       , legend=c("-1","-3","-5")
       , pch=1, pt.cex=c(.8,3*.8,5*.8)
       , cex=1.1
       , col="black"
       , bty="n", title="Water\nPotential\n(MPa)")

legend(x=-4150, y=-369470, xpd=NA
       , legend=c("blue","live")
       , pch=16, pt.cex=1.5
       , cex=1.1
       , col=c(bluecol, livecol)
       , bty="n")
```


```{r}
# predawn from July
# bluecol <- paste0(brewer.pal(n=3,"Set1")[2],"AA")
# livecol <- paste0(brewer.pal(n=3,"Set1")[1],"88")
plot(demLL, col= grey(1:150/150)[51:150], legend=F
     , main="July"
     , yaxt="n", xaxt="n")
contour(demLL, add=T)
points(wp_ind_utm[which(wp_ind_utm$species=="blue oak" & wp_ind_utm$week==29),]
       , pch=21
       , cex=wp_ind_utm$pd_mpa[which(wp_ind_utm$species=="blue oak" & wp_ind_utm$week==29)]*.8
       , bg=bluecol)
points(wp_ind_utm[which(wp_ind_utm$species=="live oak" & wp_ind_utm$week==29),]
       , pch=21
       , cex=wp_ind_utm$pd_mpa[which(wp_ind_utm$species=="live oak" & wp_ind_utm$week==29)]*.8
       , bg=livecol)
# legend(x=-4150, y=-369600, xpd=NA
#        , legend=c("-1","-3","-5")
#        , pch=1, pt.cex=c(.8,3*.8,5*.8)
#        , cex=1.1
#        , col="black"
#        , bty="n", title="Water\nPotential\n(MPa)")
# 
# legend(x=-4150, y=-369400, xpd=NA
#        , legend=c("blue","live")
#        , pch=16, pt.cex=1.5
#        , cex=1.1
#        , col=c(bluecol, livecol)
#        , bty="n")
```


```{r}
##### Midday Map through Time #####
#quartz(width=8, height=5)
#par(mfrow=c(1,2))
# midday from April
# bluecol <- paste0(brewer.pal(n=3,"Set1")[2],"AA")
# livecol <- paste0(brewer.pal(n=3,"Set1")[1],"88")
plot(demLL, col= grey(1:150/150)[51:150], legend=F
     , main="April"
     , xaxt="n",yaxt="n"
     , ylab="")
mtext(side=2, "Tree Stress", font=2, line=1.5, cex=1.2)
contour(demLL, add=T)
points(wp_ind_utm[which(wp_ind_utm$species=="blue oak" & wp_ind_utm$week==15),]
       , pch=21
       , cex=wp_ind_utm$md_mpa[which(wp_ind_utm$species=="blue oak" & wp_ind_utm$week==15)]*.8
       , bg=bluecol)
points(wp_ind_utm[which(wp_ind_utm$species=="live oak" & wp_ind_utm$week==15),]
       , pch=21
       , cex=wp_ind_utm$md_mpa[which(wp_ind_utm$species=="live oak" & wp_ind_utm$week==15)]*.8
       , bg=livecol)
par(xpd=NA)
arrows(x0=-4100, y0=-369450, y1=-369380, xpd=NA, lwd=2,length=.2 )
text("N", font=2, x=-4100, y=-369360, cex=1.8)
par(xpd=T)
legend(x=-4150, y=-369600, xpd=NA
       , legend=c("-1","-3","-5")
       , pch=1, pt.cex=c(.8,3*.8,5*.8)
       , cex=1.1
       , col="black"
       , bty="n", title="Water\nPotential\n(MPa)")

legend(x=-4150, y=-369470, xpd=NA
       , legend=c("blue","live")
       , pch=16, pt.cex=1.5
       , cex=1.1
       , col=c(bluecol, livecol)
       , bty="n")


# midday from July
# bluecol <- paste0(brewer.pal(n=3,"Set1")[2],"AA")
# livecol <- paste0(brewer.pal(n=3,"Set1")[1],"88")
plot(demLL, col= grey(1:150/150)[51:150], legend=F
     , main="July"
     , xaxt="n",yaxt="n")
contour(demLL, add=T)
points(wp_ind_utm[which(wp_ind_utm$species=="blue oak" & wp_ind_utm$week==29),]
       , pch=21
       , cex=wp_ind_utm$md_mpa[which(wp_ind_utm$species=="blue oak" & wp_ind_utm$week==29)]*.8
       , bg=bluecol)
points(wp_ind_utm[which(wp_ind_utm$species=="live oak" & wp_ind_utm$week==29),]
       , pch=21
       , cex=wp_ind_utm$md_mpa[which(wp_ind_utm$species=="live oak" & wp_ind_utm$week==29)]*.8
       , bg=livecol)

# Highlight trees past P50
points(wp_ind_utm[which(wp_ind_utm$species=="live oak" & wp_ind_utm$week==29 & wp_ind_utm$md_mpa> P50ag),]
       , pch=21, lwd=3
       , cex=wp_ind_utm$md_mpa[which(wp_ind_utm$species=="live oak" & wp_ind_utm$week==29& wp_ind_utm$md_mpa> P50ag)]*.8
       , bg=livecol, col=p50col)#brewer.pal(n=3,"Set1")[1]) #"#FFC107")
points(wp_ind_utm[which(wp_ind_utm$species=="blue oak" & wp_ind_utm$week==29 & wp_ind_utm$md_mpa> P50doug),]
       , pch=21, lwd=3
       , cex=wp_ind_utm$md_mpa[which(wp_ind_utm$species=="blue oak" & wp_ind_utm$week==29& wp_ind_utm$md_mpa> P50doug)]*.8
       , bg=bluecol , col= p50col)#brewer.pal(n=3,"Set1")[1])

# legend(x=-4150, y=-369600, xpd=NA
#        , legend=c("-1","-3","-5")
#        , pch=1, pt.cex=c(.8,3*.8,5*.8)
#        , cex=1.1
#        , col="black"
#        , bty="n", title="Water\nPotential\n(MPa)")
# 
# legend(x=-4150, y=-369400, xpd=NA
#        , legend=c("blue","live")
#        , pch=16, pt.cex=1.5
#        , cex=1.1
#        , col=c(bluecol, livecol)
#        , bty="n")
```



