---
title: "Establishing relationships between cwc and MPa, Part 2"
author: "Indra Boving"
date: "11/9022"
output:
  html_document: default
  word_document: default
---

#Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
library(tidyverse)
library(boot)
source(here::here("scripts", "scripts_functions", "figure_info.R"))

library(data.table)
library(janitor)
library(here)
library(tidyverse)
library(lubridate)
library(readxl)
library(gridExtra)
library(calecopal)
library(rstatix)
library(vars)
library(MuMIn)
library(lme4) #for mixed effects models
library(arm)
library(nlme)
select = dplyr::select

library(cowplot)
library(grid)
library(gridExtra)

#source(here::here("scripts", "scripts_functions", "figure_info.R"))

datver <- "20230724" #make sure this matches the datver in the processing script
dataversion <- paste0("Data_", datver)
```


#DATA - CWC: 

```{r}
data_og <- read_csv(here("processed-data", paste0("cwc_analysis",datver,".csv")), show_col_types = F) %>%  
  filter(species %in% c("live oak")) %>% 
  select(tree, week, water_potential, cwc, time_season, time, site, date_wp) %>% 
  distinct() %>% 
   # filter(!tree %in% c(2012, 2011)) %>% 
 # filter(!(tree %in% c(2346))) %>% #this tree seems to have a problem with post-leafout cwc - all 0s - likely becuase the canopy was too small to see. 
  filter(!week %in% 11) #week 11 only has 9 midday measurements and acts really odd (2022-03-15) 
```
#--------------
#----------
#FIGURES

#LWC

####Space

Bootstrapped: 
```{r}
final_df_all_lwc <-  read_csv(here::here("processed-data", "bootstrapped_df_quag_lwc_mean.csv")) %>% 
  filter(!(week == 33))


space_slope_bs_lwc <-  final_df_all_lwc  %>% 
   #filter(!week %in% c(9, 18)) %>% 
  filter(analysis == "space") %>% 
 # mutate(week = as.numeric(week)) %>% 
   ggplot(aes(color= as.factor(week))
    ) + 
  #  geom_rect(ymin = 12.3, ymax = 18, 
  #         xmin = -Inf, xmax = Inf, fill = "#969696", alpha = .01, color = NA) +
  # geom_hline(aes(yintercept = 15, color = "#525252")) + 
  geom_point(aes(y = slope ,x = as.factor(week)), size =2) +
    geom_point(aes(y = upr, x = as.factor(week)), size = 1) +
  geom_point(aes(y = lwr, x = as.factor(week)), size = 1) +
  #geom_line(aes(group = week, y = week, x = upr)) +
  geom_segment(aes(y= lwr, 
                   yend = upr, 
                   x = as.factor(week), 
                   xend = as.factor(week), 
                   color = as.factor(week)))+
  labs(x = "Week", 
       color = "Week", 
       y = " ") +
  theme(legend.position="none",
      strip.background = element_blank(),
      strip.text.x = element_text(size = 12),
      plot.title = element_text(size=13),
      axis.title.y = element_blank(),
      axis.title.x = element_blank(),
     axis.text = element_text(size = 12),
     legend.key=element_blank(), 
     legend.text = element_text(size = 13), 
    # legend.title = element_text(size = 16),
    legend.title = element_blank(),
     legend.margin=margin(0,0,0,0),
      legend.box.margin=margin(-5,-8,-8,-8),
    plot.margin = unit(c(5.5, 5.5, 0, 5.5), units = "pt")
    ) +
  #scale_x_continuous(breaks = c(10, 12, 14,15, 17, 19, 21, 29, 33, 37)
                  #   breaks = c(37, 33, 29, 21, 19, 17, 15, 14, 12, 10)
                      # seq(10, 30, by = 1)
  #                   ) +
  geom_hline(yintercept = 0, linetype="dotted") + 
  color_week_assigned+
 # color_many_2 +
  guides(color = guide_legend(nrow = 2)) #+
  #ylim(-8, 35)
 # scale_x_reverse()
space_slope_bs_lwc
```


####Time

BS:

```{r}
time_summary_lwc <- final_df_all_lwc  %>% 
   filter(!week %in% c(9, 33)) %>% 
  filter(analysis == "time, ind. tree") %>% 
   mutate(week = as.factor(week), 
          time_season = case_when(
            time_season %in% c("before leafout") ~ "During", 
             time_season %in% c("after leafout") ~ "After", 
            
          )) %>% 
ggplot(aes(color = time_season)) + 
  #  geom_rect(ymin = 12.3, ymax = 18, 
  #         xmin = -Inf, xmax = Inf, fill = "#969696", alpha = .05, color = NA) +
  # geom_hline(aes(yintercept = 15), color = "darkgrey") + 
  geom_point(aes(y = slope, x = time_season), size =3) +
  geom_point(aes(y = upr, x = time_season), size = 1) +
  geom_point(aes(y = lwr, x = time_season), size = 1) +
  geom_segment(aes(y= lwr, 
                   yend = upr, 
                   x = time_season, 
                   xend = time_season)) +
  labs(y = "",
       x = "Time") +
  color_two_grey +
  geom_hline(yintercept = 0, linetype="dotted") + 
  theme(legend.position="none",
      strip.background = element_blank(),
      strip.text.x = element_text(size = 12),
      plot.title = element_text(size=13),
      axis.title.y = element_blank(),
      #axis.title.x = element_text(size = 13),
      axis.title.x = element_blank(),
     axis.text = element_text(size = 12),
     legend.key=element_blank(), 
     legend.text = element_text(size = 13), 
     legend.title = element_text(size = 16),
     legend.margin=margin(0,0,0,0),
      legend.box.margin=margin(-5,-8,-8,-8),
     plot.margin = unit(c(5.5, 5.5, 0, 5.5), units = "pt")
    ) +
  scale_x_discrete(limits = rev)

time_summary_lwc
```


#CWC
####Space

```{r}
final_df_all_cwc <- read_csv(here::here("processed-data", "bootstrapped_df_cwc.csv")) %>% 
  filter(!(week %in% c(33)))

space_slope <-  final_df_all_cwc %>% 
   filter(!week %in% c(9)) %>% 
  filter(analysis == "space") %>% 
 # mutate(week = as.numeric(week)) %>% 
   ggplot(aes(color= as.factor(week))
    ) + 
  geom_point(aes(y = slope ,x = as.factor(week)), size =2) +
    geom_point(aes(y = upr, x = as.factor(week)), size = 1) +
  geom_point(aes(y = lwr, x = as.factor(week)), size = 1) +
  #geom_line(aes(group = week, y = week, x = upr)) +
  geom_segment(aes(y= lwr, 
                   yend = upr, 
                   x = as.factor(week), 
                   xend = as.factor(week), 
                   color = as.factor(week)))+
  labs(x = "Week", 
       color = "Week", 
       y = " ") +
  theme(legend.position="none",
       # legend.position= c(.7, .2),
      strip.background = element_blank(),
      strip.text.x = element_text(size = 12),
      plot.title = element_text(size=13),
     # axis.title = element_text(size = 16),
     axis.text.y = element_text(size = 12),
     axis.text.x = element_text(size = 12),
    # axis.text.x  = element_blank(),
     legend.key=element_blank(), 
      axis.title.x = element_blank(),
     axis.title.y = element_blank(),
     legend.text = element_text(size = 13), 
     legend.title = element_text(size = 16),
     legend.margin=margin(0,0,0,0),
      legend.box.margin=margin(-5,-8,-8,-8),
    plot.margin = unit(c(5.5, 5.5, 0, 5.5), units = "pt")
    ) +
  #scale_x_continuous(breaks = c(10, 12, 14,15, 17, 19, 21, 29, 33, 37)
                  #   breaks = c(37, 33, 29, 21, 19, 17, 15, 14, 12, 10)
                      # seq(10, 30, by = 1)
  #                   ) +
  geom_hline(yintercept = 0, linetype="dotted") + 
  color_week_assigned +
 # color_many_2 +
  guides(color = guide_legend(nrow = 2))
 # scale_x_reverse()
space_slope

```


####Time

BS:

```{r}
time_summary <- final_df_all_cwc%>% 
   filter(!week %in% c(9)) %>% 
  filter(analysis == "time, ind. tree") %>% 
   mutate(week = as.factor(week), 
          time_season = case_when(
            time_season %in% c("before leafout") ~ "During", 
             time_season %in% c("after leafout") ~ "After", 
            
          )) %>% 
ggplot(aes(color = time_season)) + 
  geom_point(aes(y = slope, x = time_season), size =3) +
  geom_point(aes(y = upr, x = time_season), size = 1) +
  geom_point(aes(y = lwr, x = time_season), size = 1) +
  geom_segment(aes(y= lwr, 
                   yend = upr, 
                   x = time_season, 
                   xend = time_season)) +
  labs(y = "",
       x = "Time") +
  color_two_grey +
  geom_hline(yintercept = 0, linetype="dotted") + 
  theme(legend.position="none",
       # legend.position= c(.7, .2),
      strip.background = element_blank(),
      strip.text.x = element_text(size = 12),
      plot.title = element_text(size=13),
     # axis.title = element_text(size = 16),
     axis.text.y = element_text(size = 12),
     axis.text.x = element_text(size = 12),
    # axis.text.x  = element_blank(),
     legend.key=element_blank(), 
      axis.title.x = element_blank(),
     axis.title.y = element_blank(),
     legend.text = element_text(size = 13), 
     legend.title = element_text(size = 16),
     legend.margin=margin(0,0,0,0),
      legend.box.margin=margin(-5,-8,-8,-8),
    plot.margin = unit(c(5.5, 5.5, 0, 5.5), units = "pt")
    ) +
  scale_x_discrete(limit = rev)
  
time_summary
```




######Legend:

```{r}
legend_plot <- data_og %>% 
  mutate(time = case_when(
    time == "md" ~ "Midday", 
    time == "pd" ~ "Predawn"
  )) %>% 
  filter(time == "Midday") %>% 
  filter(!(week == 9)) %>% 
  drop_na(week) %>% 
  ggplot(aes(y = water_potential,
             x = cwc,
             color = as.factor(week), 
            # shape = as.factor(time),
             )) +
  geom_point() +
  theme(legend.position="top",
       # legend.position= c(.7, .2),
      strip.background = element_blank(),
      strip.text.x = element_text(size = 12),
      plot.title = element_text(size=13),
     # axis.title = element_text(size = 16),
     axis.text = element_text(size = 12),
     legend.key=element_blank(), 
     axis.title.x = element_blank(),
     axis.title.y = element_blank(),
     legend.text = element_text(size = 13), 
     legend.title = element_text(size = 16),
     legend.margin=margin(0,0,0,0),
    legend.box.margin=margin(-5,-8,-8,-8)
    ) +
  geom_smooth(method = "lm", se = F, size = .5) + 
  labs(color = "Week", 
       shape = "Time") +
  color_week_assigned +
 # ylim(0,2) +
  guides(color = guide_legend(nrow = 2))
legend_plot

legend_scatterplots <- cowplot::get_legend(legend_plot)
legend_scatterplots
```


#COMBINE
```{r}
#SPACE
#labels of slopes: 
y.grob1 <- textGrob("Slope", 
                   gp=gpar(fontface="bold", #col="blue", 
                           fontsize=15), rot=90)

x.grob1 <- textGrob("Time", 
                   gp=gpar(fontface="bold", #col="blue", 
                           fontsize=15))

combined_slopes_wide <- cowplot::plot_grid(space_slope_bs_lwc, NULL, time_summary_lwc,
                                           # NULL, pv_slope,
                                   nrow = 1, 
                                  rel_widths = c(1, -.005, .5  #, -.02, .5
                                                 ), 
                                  labels = c("A", "", "B"#,"", "G"
                                             ),
                                  label_x = .1,
                                  hjust= c(-1, 0, -1),
                                  label_y = .98
                                  # rel_heights = c(.15, 1, .3), 
                                   #rel_widths = c(1, 1, 1), 
                                  # rel_widths = c(.7, .8, .7, .3)
                                   ) 

combined_slopes_wide
#labels of scatterplots: 
y.grob2 <- textGrob("Water Potential (MPa)", 
                   gp=gpar(fontface="bold", #col="blue", 
                           fontsize=15), rot=90)

x.grob2 <- textGrob("Leaf Water Content (g)", 
                   gp=gpar(fontface="bold", #col="blue",
                           fontsize=15))

combined_plots_wide_labels_lwc <- grid.arrange(arrangeGrob(combined_slopes_wide, 
                                #left = y.grob2, 
                                bottom = x.grob2,
                                heights = c(1, 0)))

#labels of slopes: 
y.grob1 <- textGrob("Slope", 
                   gp=gpar(fontface="bold", #col="blue", 
                           fontsize=15), rot=90)

x.grob1 <- textGrob("Time", 
                   gp=gpar(fontface="bold", #col="blue", 
                           fontsize=15))

combined_slopes_wide <- cowplot::plot_grid(space_slope, NULL, time_summary,
                                           # NULL, pv_slope,
                                   nrow = 1, 
                                  rel_widths = c(1, -.005, .5  #, -.02, .5
                                                 ), 
                                  labels = c("C", "", "D"#,"", "G"
                                             ),
                                  label_x = .1,
                                  hjust= c(-.6, 0, -1),
                                  label_y = .98
                                  # rel_heights = c(.15, 1, .3), 
                                   #rel_widths = c(1, 1, 1), 
                                  # rel_widths = c(.7, .8, .7, .3)
                                   ) 

combined_slopes_wide
#labels of scatterplots: 
y.grob2 <- textGrob("Slope", 
                   gp=gpar(fontface="bold", #col="blue", 
                           fontsize=15), rot=90)

x.grob2 <- textGrob("Canopy Water Content (g/cm2)", 
                   gp=gpar(fontface="bold", #col="blue",
                           fontsize=15))

combined_plots_wide_labels <- grid.arrange(arrangeGrob(combined_slopes_wide, 
                               # left = y.grob2, 
                                bottom = x.grob2,
                                heights = c(1, 0)))


quag_plot_slopes <- cowplot::plot_grid(combined_plots_wide_labels_lwc,
                                       combined_plots_wide_labels,
                                       nrow = 2)
quag_plot_slopes

quag_plot_slopes_final <- grid.arrange(arrangeGrob(quag_plot_slopes,
                                top = legend_scatterplots,
                                left = y.grob2, 
                                heights = c(1, 0)))

legend_scatterplots

ggsave(here("figures", "quag figures", "slopes_space_time_quag"), quag_plot_slopes_final, device = "jpg", width = 6, height = 4, dpi = 300)
```

####SWC and LMA: 

```{r, fig.height=2, fig.width=6}
##USE THIS ONE: 
#lma_plot <- data_qudo_raw %>% 
lma_plot_df <- read_csv(here("processed-data", paste0("wp_wc_rwc_",datver,".csv"))) %>% 
  filter(year_alas %in% c(0), 
         year_rwc %in% c(0))


lma_plot <- lma_plot_df  %>% 
   # select(mean_swc_per_dry_g, lma_g_cm2, species, week, week_alas_link, year_alas,year_rwc) %>% 
  drop_na(mean_swc_per_dry_g) %>% 
  distinct() %>% 
  mutate(week_alas_link = case_when(
    week_alas_link %in% c(11) ~ 10, 
    week_alas_link %in% c(13) ~ 14, 
    TRUE ~ as.numeric(week_alas_link)
  )) %>% 
    group_by(week_alas_link, species#, year_alas, year_rwc
             ) %>% 
  # mutate(mean_swc_per_dry_g  = scale(mean_swc_per_dry_g), 
  #        lma_g_cm2 = scale(lma_g_cm2)) %>% 
 # select(mean_swc_per_dry_g, lma_g_cm2, species, week, year_alas) %>% 
  mutate(#lma_all = lma_g_cm2_new,
         lma_g_cm2 = mean(lma_g_cm2, na.rm = T), 
         mean_swc_per_dry_g = mean(mean_swc_per_dry_g, na.rm = T)
        # year_rwc = as.factor(year_rwc), 
       #  year_alas = as.factor(year_alas)
       ) %>% 
  filter(species %in% c("live oak")) %>% 
  #filter(lma_g_cm2 < 0.08) %>% 
  # select(week, #species, 
  #        year_alas, 
  #        lma_g_cm2,
  #         mean_swc_per_dry_g) %>% 
  distinct() %>% 
  drop_na(lma_g_cm2)  %>%
 # filter(week %in% c(10, 11, 13, 14, 17, 21, 29, 37, 40)) %>% 
  ggplot() +
  geom_point(aes(x = week_alas_link, 
              #  shape = year_alas, 
             y = lma_g_cm2  * 43, #need a scaling factor to bring lma up to swc
             #color = species
             ),
             size = 3) +
  geom_line(aes(x = week_alas_link, 
             y = lma_g_cm2 * 43, 
           #  line_type = year_alas,
             #color = species
             )) +
  geom_point(aes(x = week_alas_link, 
             y = mean_swc_per_dry_g, 
             color = "darkgrey",
            # shape = year_rwc, 
             #color = species
             ),
                shape = 17,
             size = 3,
            color = "darkgrey") +
  geom_line(aes(x = week_alas_link, 
             y =mean_swc_per_dry_g, 
            # linetype = year_rwc, 
             group = species
             #color = species
             ),
            color = "darkgrey") +
  scale_x_continuous(breaks = c(10, 14, 21, 29, 37)) +
  labs(y = "LMA (g/cm2)", 
       x = "Week") +
  theme(legend.position = "none",
        axis.title.y = element_blank(), 
       # axis.title.x = element_text(size = 13), 
        axis.title.x = element_blank(), 
        axis.text.x = element_text(size = 13), 
       # axis.title.x = element_blank(), 
        axis.text.y = element_blank(),
        axis.ticks = element_blank(), 
       # axis.text.x = element_text(hjust=.5, size= 20)
        )
lma_plot

y.grob <- textGrob("SWC (g)", 
                   gp=gpar(col="#525252", 
                           fontsize=15,
                           fontface="bold"), 
                   rot=90)

y.grob2 <- textGrob("LMA (g/cm2)", 
                   gp=gpar(col="black", 
                           fontface="bold",
                           fontsize=15), 
                   rot=90)

x.grob2 <- textGrob("Week", 
                   gp=gpar(col="black", 
                           fontface="bold",
                           fontsize=15), 
                   rot=0)

lma_swc_plot <- grid.arrange(arrangeGrob(lma_plot,
                            right = y.grob, 
                            left = y.grob2,
                            bottom = x.grob2,
                            heights = c(1, 0), 
                            widths = c(1.5, 0)))


ggsave(here("figures", "quag figures", "lma_long_plot"), lma_swc_plot, device = "jpeg", width = 6, height = 1.75, dpi = 300)
```

#COMBINE ALL: 

```{r}
plot <- cowplot::plot_grid(quag_plot_slopes_final,
                           lma_swc_plot, 
                           nrow = 2, 
                           rel_heights = c(.9, .3))
plot

ggsave(here("figures", "quag figures", "quag_fig_plot"), plot, device = "jpeg", width = 7, height = 5, dpi = 300)
```



