---
title: "Mapping water pots"
author: "Indra Boving"
date: "6/3/2022"
output: html_document
---

##setup

```{r setup, include=FALSE}
library(data.table)
library(janitor)
library(here)
library(tidyverse)
library(lubridate)
library(readxl)
library(gridExtra)
library(MetBrewer)
library(raster)
library(paletteer) 
library(RColorBrewer)
library(ggmap)
library(rgdal)
library(sf)
library(sp)

# get rid of horrible grid lines but don't have to set Theme each time
### sets default ggplot so that there's no brown grid in the background
ggplot <- function(...) { ggplot2::ggplot(...) + 
    theme(panel.background = element_rect(fill='white', colour='black'), # Make background white and border black
          panel.grid.major = element_blank(),  # Hide major gridlines
          panel.grid.minor = element_blank())  # Hide minor gridlines
}
```

Code stolen from Cd-WaterPotentialCleaning.R (thanks Lee!)

```{r}
datver <- "08182022"
dataversion <- paste0("Data_", datver)

# Indra's version
wp_alldates <- read.csv(here("processed-data", paste0("wp_alldates_",datver,".csv")))

# lee's version
wp_ad <- read.csv(here("processed-data", paste0("wp_alldates_long_",datver,".csv")))[,-1]
wp_ad$tag <- str_replace(wp_ad$tag, "\\.0","") # get rid of annoying .0 at end of numeric tags (thanks excel)

## table for linking tree numbers with sites, correct some mislabeling
treesite <- read_excel(here(dataversion,"WP_WC","SHIFT data collection 2022.xlsx"),sheet="Tree_Sites", skip=0, na = "NA", col_types = "text")
treesite$Tag <- str_replace(treesite$Tag, "\\.0","")
wp_ad$plot <- treesite$Plot[match(wp_ad$tag, treesite$Tag)]

###### Sedgwick DEM
sdem <- raster::raster("Data_05042022/geospatial/DEM_sedgwick_3m.tif")
#sdemll <- st_transform(sdem, crs= 4326)
#sdemll <- raster::projectRaster(sdem)
# make a df for plotting with ggplot
sdem_gg <- sdem %>%
  rasterToPoints() %>%
  data.frame()

#### Tree Locations
latlon <- read.csv(here("Data_05042022", "Trees_LatLon_v2.csv"))
colnames(latlon)[1:2] <- c("Longitude","Latitude")
# pull out 'B' and 'L' at start of tree names
latlon$Tree <- latlon$Name
latlon$Tree <- str_remove(pattern="B", string=latlon$Tree)
latlon$Tree <- str_remove(pattern="L", string=latlon$Tree)
# make this a seperate species column
latlon$Species <- NA
latlon$Species[grep("B",latlon$Name )] <- "B"
latlon$Species[grep("L",latlon$Name )] <- "L"
# fix shrub names
latlon$Species[grep("Art",latlon$Name)] <- "ARCA"
latlon$Species[grep("LE",latlon$Name)] <- "LEU"
latlon$Tree[which(latlon$Species=="ARCA")] <- c("Chamise-ARCA","Cucu-ARCA","LL-ARCA")
latlon$Tree[which(latlon$Species=="LEU")] <- c("Cucu-LEU","LL-LEU")
latlon$Tree[grep("Dont", latlon$Name)] <- "2373"
```

^Above all works!^

Below does not: ?

```{r}
# make a latlon and utm spatial data version
latlon.ll <- SpatialPointsDataFrame(coords = data.frame(latlon$Longitude, latlon$Latitude), 
                                    proj4string = CRS("+proj=longlat +datum=WGS84"), data=latlon)
latlon.ll_assf <- st_as_sf(latlon.ll)
latlon.utm <- st_transform(latlon.ll,
                           CRSobj = crs(sdem))
```


```{r}
##That wasnt working, so try a new way: 

latlon.ll.new <- st_sf(coords = st_as_sfc(data.frame(latlon$Longitude, latlon$Latitude)), 
                       crs = 
                       data=latlon)

st_transform(sdem, crs= 4326)
latlon.utm <- st_transform(latlon.ll, sdem)
```


```{r}
P50doug <- 4.43 # average of all of our wild curves from Skelton et al. 2019 NP
P50ag <- 4.32 # from Skelton et al. 2018 Plant Phys
```

