

Scatterplots:

```{r}
df_all_groups <- wk_figs %>% 
  mutate(tree_week = paste(tree, week, sep = "_")
  ) %>% 
  mutate(water_potential = water_potential)
  
df_grey <- df_all_groups

df_1 <- df_all_groups %>% 
  filter(week %in% c('10'))

df_2 <- df_all_groups %>% 
  filter(week %in% c('17'))

df_3 <- df_all_groups %>% 
  filter(week %in% c('21'))

df_4 <- df_all_groups %>% 
  filter(week %in% c('37'))

nice_hydration_layered_1 <- ggplot() +
    geom_point(aes(y = water_potential, x = lwc, shape = time), data = df_grey, color = "grey") +
    geom_line(aes(y = water_potential, x = lwc, group = tree_week), color = "grey", data = df_grey) +
    geom_point(aes(y = water_potential, x = lwc, shape = time, color = "df_1"), 
               data = df_1 ) +
    geom_line(aes(y = water_potential, x = lwc, group = tree_week, color = "df_1"), 
              data = df_1) +
    geom_point(aes(y = water_potential, x = lwc, shape = time, color = "df_2"), 
               data = df_2) +
    geom_line(aes(y = water_potential, x = lwc, group = tree_week, color = "df_2"), 
              data = df_2) +
    geom_point(aes(y = water_potential, x = lwc, shape = time, color = "df_4"), 
               data = df_4) +
    geom_line(aes(y = water_potential, x = lwc, group = tree_week, color = "df_4"), 
              data = df_4
              ) +
    scale_colour_manual(name = 'Week', 
         values =c("df_1" ="#122451", 
                   "df_2"="#D9B150",
                  # "df_3"="#EC7E28",
                   "df_4"="#c969a1"
                   ), 
         labels = c('10',
                    '17',
                  #  '21',
                    '33')) +
    labs(y = "Water Potential (MPa)", 
       x = "Leaf Water Content (g)", 
       color= "Week", 
       shape = "Time"
       #caption = "triangles = predawn, circles = midday"
       ) +
  theme(
    #legend.position = c(.9, .35),
    legend.position = "none",
  #strip.background = element_blank(),
  #strip.text.y = element_blank(), 
  #strip.text.x = element_text(size = 16), 
  # axis.text.y = element_text(size = 12), 
  # axis.text.x = element_text(size = 12), 
   axis.text.y = element_text(size = 12),
     axis.text.x  = element_blank(),
  #axis.ticks.y = element_blank(), 
  axis.title.y = element_text(size = 15), 
  axis.title.x = element_blank(),
  legend.title = element_text(size = 14), 
  legend.text = element_text(size = 14), 
# legend.position = "none"
  ) +
   ylim(-5,0)+
   xlim(.5,2) #+
#nice_hydration_layered_1


####***SPACE - fig: 

#scaled
space_nice_1 <- wc_wk_centered_df %>% 
  drop_na(site) %>% 
  ggplot(aes(y = water_potential, 
            # x = lwc_centered, 
            x = lwc,
             #color = tree_factor
             color = as.factor(week)
             )) +
  geom_point(alpha = .5, 
            # aes (shape = site)
             ) +
  theme(legend.position="none",
       # legend.position= c(.7, .2),
      strip.background = element_blank(),
      strip.text.x = element_text(size = 12),
      plot.title = element_text(size=13),
     # axis.title = element_text(size = 16),
     axis.text.y = element_text(size = 12),
     axis.text.x  = element_blank(),
     legend.key=element_blank(), 
      axis.title.x = element_blank(),
     axis.title.y = element_text(size = 15), 
     legend.text = element_text(size = 13), 
     legend.title = element_text(size = 16),
     legend.margin=margin(0,0,0,0),
      legend.box.margin=margin(-5,-8,-8,-8)
    ) +
  geom_smooth(method = "lm", se = F,size = .5) + 
 # geom_vline(xintercept = 0, linetype = "dotted") +
  labs(y= "Middays (MPa)", 
       x = "Leaf Water Content", 
       color = "Week", 
       shape = "Site") +
  color_many_2 +
  xlim(.5,2) +
  ylim(-5,0)+
  guides(color = guide_legend(nrow = 2))
#space_nice_1



#Time: 

time_1 <- wc_qudo_df %>% 
  mutate(time = case_when(
    time == "md" ~ "Midday", 
    time == "pd" ~ "Predawn"
  )) %>% 
  filter(time == "Midday") %>% 
  drop_na(week) %>% 
 # filter(time == "md") %>% 
  ggplot(aes(y = water_potential, 
             x = lwc, 
             color = time_season, 
             size = week,
             shape = as.factor(tree),
             show.legend = FALSE)) +
  geom_point(size = 1,
             alpha = .3)+
  geom_smooth(method = "lm", se = F, size = .5, alpha = .4) +
 # theme(legend.position = "none") +
  labs(x = "LWC", 
       y = "Midday MPa") +
  #color_two_grey +
  theme(
      legend.position="none",
      strip.background = element_blank(),
     # strip.text.x = element_text(size = 12),
      strip.text.x = element_text(size = 12),
      plot.title = element_text(size=13),
      axis.title = element_text(size = 15),
     axis.text = element_text(size = 12),
     legend.key=element_blank(), 
     legend.text = element_text(size = 13), 
     legend.title = element_text(size = 16),
     legend.margin=margin(0,0,0,0),
      legend.box.margin=margin(-5,-8,-8,-8)
    ) +
  labs(y= "Water Potential (MPa)", 
       x = "Leaf Water Content (g)", 
       color = "Week", 
       ) +
  guides(color = guide_legend(nrow = 2)) +
 # facet_wrap(~time, nrow = 2) +
   xlim(.5,2) +
  ylim(-5,0)+
  color_two_grey

#time_1 


##COMBINE:


legend_plot <- wc_wk_centered_df %>% 
  drop_na(site) %>% 
  ggplot(aes(y = water_potential,
            x = lwc,
             color = as.factor(week)
             )) +
  geom_point(alpha = .5) +
  theme(legend.position="top",
       # legend.position= c(.7, .2),
      strip.background = element_blank(),
      strip.text.x = element_text(size = 12),
      plot.title = element_text(size=13),
     # axis.title = element_text(size = 16),
     axis.text = element_text(size = 12),
     legend.key=element_blank(), 
      axis.title.x = element_blank(),
     axis.title.y = element_text(size = 15), 
     legend.text = element_text(size = 13), 
     legend.title = element_text(size = 16),
     legend.margin=margin(0,0,0,0),
    legend.box.margin=margin(-5,-8,-8,-8)
    ) +
  geom_smooth(method = "lm", se = F, size = .5) + 
  labs(color = "Week") +
  color_many_2 #+
 # ylim(0,2) +
 # guides(color = guide_legend(nrow = 2))
legend_plot

legend_scatterplots <- cowplot::get_legend(legend_plot)
legend_scatterplots


stacked_nice <- cowplot::plot_grid(space_nice_1, nice_hydration_layered_1, time_1, 
                                   nrow = 3, rel_heights = c(2, 2, 2)) 

stacked_nice

final<- cowplot::plot_grid(legend_scatterplots, stacked_nice, nrow = 2, rel_heights  = c(.25, 4))
final

ggsave(here("figures", "nice_all"), final, device = "jpg", width = 5, height = 10, dpi = 300)
```


#Slopes: 

```{r}
hyd_slopes <- ran_df_week %>% 
  filter(!week %in% c(9)) %>% 
 # filter(week %in% c(14, 17, 21, 29)) %>% 
 # filter(term == "lwc") %>% 
  mutate(upr = slope + (std.error.slope/2), 
         lwr = slope - (std.error.slope/2)) %>% 
  ggplot(aes(color= week)
    ) + 
  geom_point(aes(y = slope ,x = week), size =2) +
    geom_point(aes(y = upr, x = week), size = 1) +
  geom_point(aes(y = lwr, x = week), size = 1) +
  #geom_line(aes(group = week, y = week, x = upr)) +
  geom_segment(aes(y= lwr, 
                   yend = upr, 
                   x = week, 
                   xend = week, 
                   color = week))+
  labs(#x = "Week", 
       color = "week", 
       y = "Slope") +
   # facet_wrap(~y_var_name, scales = "free") + 
theme(
  strip.background = element_blank(),
  strip.text.y = element_blank(), 
  strip.text.x = element_text(size = 16), 
 # axis.text.y = element_blank(), 
  #axis.ticks.y = element_blank(), 
 axis.title.x = element_blank(),
  axis.title.y = element_text(size = 15), 
  legend.title = element_text(size = 18), 
 legend.position = "none"
  ) +
  geom_hline(yintercept = 0, linetype="dotted") + 
  scale_x_continuous(breaks = c(10, 12, 14,15, 17, 18, 19, 21, 29, 33, 37)
                      # seq(10, 30, by = 1)
                     ) +
  theme(legend.position = "none") +
  #xlim(0, 40) +
  color_grad 
hyd_slopes


space_slope <- ran_df_week_4 %>% 
  mutate(week = as.numeric(week)) %>% 
 # filter(week %in% c(14, 17, 21, 29)) %>% 
 # filter(term == "lwc") %>% 
  mutate(upr = slope + (std.error.slope/2), 
         lwr = slope - (std.error.slope/2)) %>% 
  ggplot(aes(color= week)
    ) + 
  geom_point(aes(y = slope ,x = week), size =2) +
    geom_point(aes(y = upr, x = week), size = 1) +
  geom_point(aes(y = lwr, x = week), size = 1) +
  #geom_line(aes(group = week, y = week, x = upr)) +
  geom_segment(aes(y= lwr, 
                   yend = upr, 
                   x = week, 
                   xend = week, 
                   color = week))+
  labs(x = "Week", 
       color = "Week", 
       y = " ") +
  theme(legend.position="none",
      strip.background = element_blank(),
      strip.text.x = element_text(size = 12),
      plot.title = element_text(size=13),
      axis.title.y = element_text(size = 15),
      axis.title.x = element_blank(),
     axis.text = element_text(size = 12),
     legend.key=element_blank(), 
     legend.text = element_text(size = 13), 
     legend.title = element_text(size = 16),
     legend.margin=margin(0,0,0,0),
      legend.box.margin=margin(-5,-8,-8,-8)
    ) +
  scale_x_continuous(breaks = c(10, 12, 14,15, 17, 19, 21, 29, 33, 37)
                      # seq(10, 30, by = 1)
                     ) +
  geom_hline(yintercept = 0, linetype="dotted") + 
  color_grad +
  guides(color = guide_legend(nrow = 2))
space_slope

#Time

ran_df_tree_before_vs_after <- bind_rows(ran_df_tree_before, ran_df_tree_after)

ef <- ran_df_tree_before_vs_after %>% 
  group_by(time_season) %>% 
  mutate( sd = sd(slope),
    slope = mean(slope), 
        # std.error = mean(std.error),
         upr = slope + sd, 
         lwr = slope - sd, 
         time_season = as.factor(time_season)) %>% 
  select(slope, upr, lwr, time_season, sd)

time_summary <- ef %>% 
ggplot(aes(color = time_season)) + 
  geom_point(aes(y = slope, x = time_season), size =2) +
    geom_point(aes(y = upr, x = time_season), size = 1) +
  geom_point(aes(y = lwr, x = time_season), size = 1) +
  #geom_line(aes(group = tree, y = tree, x = upr)) +
  geom_segment(aes(y= lwr, 
                   yend = upr, 
                   x = time_season, 
                   xend = time_season)) +
  scale_x_discrete(limits = c("Before Leafout", "After Leafout"),
                   labels = c("Before", "After")) +
  labs(#y = "Mean Slope +/- SD acrss all trees
                 #for each time frame", 
   y = "",
       x = "Time") +
  color_two_grey +
  theme(legend.position = "none", 
        axis.title.x = element_text(size = 15), 
        axis.text.x = element_text(size = 12)
        #axis.title.y = element_blank()
        )
  
time_summary


stacked_slopes_nice <- cowplot::plot_grid(space_slope, hyd_slopes, time_summary, 
                                   nrow = 3, rel_heights = c(2, 2, 2)) 

stacked_slopes_nice

final_slopes<- cowplot::plot_grid(legend_scatterplots, stacked_slopes_nice, nrow = 2, rel_heights  = c(.25, 4))
final_slopes


combined <- cowplot::plot_grid(stacked_nice, stacked_slopes_nice, ncol = 2)
combined

combined_legend <- cowplot::plot_grid(legend_scatterplots, combined, nrow = 2, rel_heights = c(.25, 4))
combined_legend
```

