---
title: "Maps"
author: "Indra Boving"
date: "02/15/2023"
output: html_document
---

##setup


```{r setup, include=FALSE}
#install.packages("rstatix")
#devtools::install_github("an-bui/calecopal")
#install.packages("tidyverse")
library(here)
library(sf)
library(raster)
library(paletteer) 
library(RColorBrewer)

# some namespace issue with raster and some of these packages.
#library(dplyr)
library(tidyverse)
library(readxl)
library(car)
library(lubridate)
library(ggmap)
library(janitor)

select = dplyr::select
 
#source("http://goo.gl/UUyEzD") #outlier KD (original function)

source(here::here("scripts","scripts_functions", "figure_info.R"))
```

#Data
```{r}
# datver <- "07192022"
# dataversion <- paste0("Data_", datver)

### Processed water potentials (individual measurements)

# Indra's version
wp_alldates <- read.csv(here("processed-data", paste0("wp_alldates_",datver,".csv")))
# lee's version
wp_ad <- read.csv(here("processed-data", paste0("wp_alldates_long_",datver,".csv")))[,-1]
wp_ad$tag <- str_replace(wp_ad$tag, "\\.0","") # get rid of annoying .0 at end of numeric tags (thanks excel)

## table for linking tree numbers with sites, correct some mislabeling
treesite <- read_excel(here(dataversion,"WP_WC","SHIFT data collection 2022.xlsx"),sheet="Tree_Sites", skip=0, na = "NA", col_types = "text")
treesite$Tag <- str_replace(treesite$Tag, "\\.0","")


wp_ad$plot <- treesite$Plot[match(wp_ad$tag, treesite$Tag)]
```

```{r}
###### Sedgwick DEM
sdem <- raster::raster(here("Data_05042022", "geospatial", "DEM_sedgwick_3m.tif"))
#sdemll <- st_transform(sdem, crs= 4326)
#sdemll <- raster::projectRaster(sdem)
# make a df for plotting with ggplot
sdem_gg <- sdem %>%
  rasterToPoints() %>%
  data.frame()

#### Tree Locations
latlon <- read.csv(here("Data_05042022", "Trees_LatLon_v2.csv"))
colnames(latlon)[1:2] <- c("Longitude","Latitude")
# pull out 'B' and 'L' at start of tree names
latlon$Tree <- latlon$Name
latlon$Tree <- str_remove(pattern="B", string=latlon$Tree)
latlon$Tree <- str_remove(pattern="L", string=latlon$Tree)
# make this a seperate species column
latlon$Species <- NA
latlon$Species[grep("B",latlon$Name )] <- "B"
latlon$Species[grep("L",latlon$Name )] <- "L"
# fix shrub names
latlon$Species[grep("Art",latlon$Name)] <- "ARCA"
latlon$Species[grep("LE",latlon$Name)] <- "LEU"
latlon$Tree[which(latlon$Species=="ARCA")] <- c("Chamise-ARCA","Cucu-ARCA","LL-ARCA")
latlon$Tree[which(latlon$Species=="LEU")] <- c("Cucu-LEU","LL-LEU")
latlon$Tree[grep("Dont", latlon$Name)] <- "2373"


# make a latlon and utm spatial data version
latlon.ll <- SpatialPointsDataFrame(coords = data.frame(latlon$Longitude, latlon$Latitude), proj4string = CRS("+proj=longlat +datum=WGS84"), data=latlon)
latlon.utm <- spTransform(latlon.ll, CRSobj = crs(sdem))


P50doug <- 4.43 # average of all of our wild curves from Skelton et al. 2019 NP
P50ag <- 4.32 # from Skelton et al. 2018 Plant Phys

############## END: Load Data ##################3
```

Data load, combine and clean: 



