---
title: "Establishing relationships between LWC and MPa, Part 2"
author: "Indra Boving"
date: "11/9022"
output:
  html_document: default
  word_document: default
---

#Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
#install.packages("")
#devtools::install_github("an-bui/calecopal")

library(data.table)
library(janitor)
library(here)
library(tidyverse)
library(lubridate)
library(readxl)
library(gridExtra)
library(calecopal)
library(rstatix)
library(vars)
library(MuMIn)
library(lme4) #for mixed effects models
library(arm)
library(nlme)
select = dplyr::select

source(here::here("scripts", "scripts_functions", "figure_info.R"))

#datver <- "01052023"
dataversion <- paste0("Data_", datver)
```

```{r, echo=F}
#wc_all_raw <- read_csv(here("processed-data", paste0("LWC_LFM_WP_dates",datver,".csv")), show_col_types = FALSE) %>% 
model_raw_df <- read_csv(here("processed-data", paste0("LWC_LFM_WP_dates",datver,".csv")), show_col_types = F) %>% 
  filter(species == "blue oak") 

model_df <- model_raw_df %>% 
   filter(#week > 15, 
        # lwc_mean < 5, 
         #lwc_mean > 0
         ) %>% 
  filter(!(week == 29 & lwc_mean > 1)) %>% 
  mutate(lwc = lwc_mean) %>% 
  group_by(tree, week, time) %>% 
  mutate(water_potential = -1*(mean(mpa_mean)), 
         tree_factor = as.factor(tree)) %>% 
  ungroup() %>% 
  mutate(week = case_when(
    week %in% c(13) ~ 14,
    week %in% c(11) ~ 10,
    TRUE ~ week
  )) %>%
  distinct() %>% 
  filter(!week == 9) %>% 
  mutate(time_season = case_when(
    week <= 17 ~ "before leafout", 
    week > 17 ~ "after leafout", 
    TRUE ~ as.character("none")
  )) %>% 
  drop_na(lwa_g_cm2, site)
```

Models: 

Hydration: 

```{r}
hyd1 <- lmer(water_potential ~ lwc + (lwc|tree) + (lwc|week), data = model_df , REML = T)

hyd2 <- lmer(water_potential ~ lwc + (lwc|tree) + (lwc|week) + (lwa_g_cm2|week), data = model_df , REML = T)

hyd3 <- lmer(water_potential ~ lwc + lwa_g_cm2 + (lwc|tree) + (lwc|week), data = model_df , REML = T)

hyd4 <- lmer(water_potential ~ lwc + lma_g_cm2 + (lwc|tree) + (lwc|week), data = model_df , REML = T)

anova(hyd1, hyd2) #1 is better
anova(hyd1, hyd3) #1 is better
anova(hyd1, hyd4) #1 is better
```

Space: 

```{r}
spc1 <- lmer(water_potential ~ lwc  + (lwc|week) + (1|tree) + (1|site), data = model_df, REML = T)

spc2 <- lmer(water_potential ~ lwc  + lma_g_cm2 + (lwc|week) + (1|tree) + (1|site), data = model_df, REML = T)

spc3 <- lmer(water_potential ~ lwc  + lwa_g_cm2 + (lwc|week) + (1|tree) + (1|site), data = model_df, REML = T)

spc4 <- lmer(water_potential ~ lwc  + (lma_g_cm2|week) + (lwc|week) + (1|tree) + (1|site), data = model_df, REML = T)

spc5 <- lmer(water_potential ~ lwc + lwa_g_cm2 + (lwa_g_cm2|week) + (1|tree) + (1|site), data = model_df, REML = T)

anova(spc1, spc2) #1 is better
anova(spc1, spc3) #1 is better
anova(spc1, spc4) #1 is better
anova(spc1, spc5) #1 is better
```

Time: 

```{r}
lmer(water_potential ~ lwc + (1|week) + (lwc|tree) + (1|site), data = wc_qudo_df, REML = T)

time1 <- lmer(water_potential ~ lwc + (1|week) + (lwc|tree) + (1|site), data = model_df, REML = T)

time2 <- lmer(water_potential ~ lma_g_cm2 + lwc + (1|week) + (lwc|tree) + (1|site), data = model_df, REML = T)

time3 <- lmer(water_potential ~ lwa_g_cm2 + lwc + (1|week) + (lwc|tree) + (1|site), data = model_df, REML = T)

time4 <- lmer(water_potential ~ lwc  + (lma_g_cm2|week) + (1|week) + (lwc|tree) + (1|site), data = model_df, REML = T)

time5 <- lmer(water_potential ~ lwc + lwa_g_cm2 + (1|week) + (lwa_g_cm2|tree) + (1|site), data = model_df, REML = T)

anova(time1, time2) #1 is better
anova(time1, time3) #1 is better
anova(time1, time4) #1 is better
anova(time1, time5) #1 is better
```




