
```{r}
library(cowplot)
library(grid)
library(gridExtra)
```

#TImeline: 

```{r, fig.height=1, fig.width=12}
timeline_df <- cwc_df %>% 
 # select(week, date_wp, time) %>% 
  mutate(date_wp = as.character(date_wp)) %>% 
  mutate(date_new = case_when(
    date_wp %in% c("2022-03-23") ~ "2022-03-25",
    date_wp %in% c("2022-03-30","2022-04-06") ~ "2022-04-04",
    date_wp %in% c("2022-04-13") ~ "2022-04-11",
    date_wp %in% c("2022-04-27") ~ "2022-04-25",
    date_wp %in% c("2022-05-04") ~ "2022-05-09",
    date_wp %in% c("2022-05-23") ~ "2022-05-25",
    TRUE ~ as.character(date_wp)
  )) %>% 
  mutate(date_new = ymd(date_new)) %>% 
  select(date_new, week) %>% 
  distinct()


timeline_plot_black <- timeline_df %>% 
 # filter(time == "md") %>% 
  ggplot(aes(x = date_new, y = 0, color = "black"))+
  geom_hline(yintercept = 0) +
  geom_point(size = 10) +
  color_week_assigned +
  ylim(-.25, +.25)  + 
  theme(legend.position = "none", 
        axis.title.y = element_blank(), 
        axis.title.x = element_blank(), 
        axis.text.y = element_blank(),
        axis.ticks = element_blank(), 
        axis.text.x = element_text(angle = 60, vjust = 0.5, hjust=.5, size= 20)
        ) +
scale_x_date(date_labels = '%b. %d',
             breaks = as.Date(c("2022-03-08","2022-03-15", "2022-03-25", 
                                #"2022-03-23", "2022-03-30", 
                                "2022-04-04", #"2022-04-06","2022-04-13", 
                                "2022-04-11", #"2022-04-27", 
                                "2022-04-25", #"2022-05-04" ,
                                "2022-05-09", "2022-05-25", 
                                #"2022-05-23", 
                                "2022-07-19", "2022-08-18","2022-09-15")))
timeline_plot_black

ggsave(here("figures", "timeline_plot_black"), timeline_plot_black, device = "jpg", width = 12, height = 2, dpi = 300)


timeline_plot_color <- timeline_df %>% 
 # filter(time == "md") %>% 
  ggplot(aes(x = date_new, y = 0, color = as.character(date_new))) +
  geom_hline(yintercept = 0) +
  geom_point(size = 10) +
  color_dates_assigned +
  ylim(-.25, +.25)  + 
  theme(legend.position = "none", 
        axis.title.y = element_blank(), 
        axis.title.x = element_blank(), 
        axis.text.y = element_blank(),
        axis.ticks = element_blank(), 
        axis.text.x = element_text(angle = 60, vjust = 0.5, hjust=.5, size= 20)
        ) +
scale_x_date(date_labels = '%b. %d',
             breaks = as.Date(c("2022-03-08","2022-03-15", "2022-03-25", 
                                #"2022-03-23", "2022-03-30", 
                                "2022-04-04", #"2022-04-06","2022-04-13", 
                                "2022-04-11", #"2022-04-27", 
                                "2022-04-25", #"2022-05-04" ,
                                "2022-05-09", "2022-05-25", 
                                #"2022-05-23", 
                                "2022-07-19", "2022-08-18","2022-09-15")))
timeline_plot_color

ggsave(here("figures", "timeline_plot_color"), timeline_plot_black, device = "jpg", width = 12, height = 2, dpi = 300)

```

#LWC: 

#Scatterplots:

#####Hydration, labels:

```{r}
df_all_groups <- wk_figs %>% 
  mutate(tree_week = paste(tree, week, sep = "_")
  ) %>% 
  mutate(water_potential = water_potential)
  
df_grey <- df_all_groups

df_1 <- df_all_groups %>% 
  filter(week %in% c('10'))

df_2 <- df_all_groups %>% 
  filter(week %in% c('17'))

df_3 <- df_all_groups %>% 
  filter(week %in% c('21'))

df_4 <- df_all_groups %>% 
  filter(week %in% c('37'))

nice_hydration_layered_esa <- ggplot() +
    geom_point(aes(y = water_potential, x = lwc, shape = time), data = df_grey, color = "grey") +
    geom_line(aes(y = water_potential, x = lwc, group = tree_week), color = "grey", data = df_grey) +
    geom_point(aes(y = water_potential, x = lwc, shape = time, color = "df_1"), 
               data = df_1 ) +
    geom_line(aes(y = water_potential, x = lwc, group = tree_week, color = "df_1"), 
              data = df_1) +
    geom_point(aes(y = water_potential, x = lwc, shape = time, color = "df_2"), 
               data = df_2) +
    geom_line(aes(y = water_potential, x = lwc, group = tree_week, color = "df_2"), 
              data = df_2) +
    geom_point(aes(y = water_potential, x = lwc, shape = time, color = "df_4"), 
               data = df_4) +
    geom_line(aes(y = water_potential, x = lwc, group = tree_week, color = "df_4"), 
              data = df_4
              ) +
    scale_colour_manual(name = 'Week', 
        values =c("df_1" = "#48578E",
                   "df_2"= "#8E9D30",
                  # "df_3"="#EC7E28",
                   "df_4"= "#E97B6E"
                   ), 
         labels = c('10',
                    '17',
                  #  '21',
                    '33')) +
    labs(y = "Water Potential (MPa)", 
         #y = " ",
       x = "Leaf Water Content (g)", 
       color= "Week", 
       shape = "Time"
       #caption = "triangles = predawn, circles = midday"
       ) +
    theme(legend.position="none",
       # legend.position= c(.7, .2),
      strip.background = element_blank(),
      strip.text.x = element_text(size = 18),
      plot.title = element_text(size=13),
     # axis.title = element_text(size = 16),
     axis.text = element_text(size = 18),
     legend.key=element_blank(), 
      axis.title.x = element_text(size = 20), 
     axis.title.y = element_text(size = 20), 
     legend.text = element_text(size = 13), 
     legend.title = element_text(size = 16),
     #legend.margin=margin(0,0,0,0),
     # legend.box.margin=margin(-5,-8,-8,-8)
    ) +
   ylim(-5,0)+
   xlim(.5,2) +
 # scale_x_reverse() +
scale_y_continuous(labels = scales::number_format(accuracy = 0.1))
nice_hydration_layered_esa
```

#####Hydration, no labels:

```{r}
nice_hydration_layered_nolabs <- ggplot() +
    geom_point(aes(y = water_potential, x = lwc, shape = time), data = df_grey, color = "grey") +
    geom_line(aes(y = water_potential, x = lwc, group = tree_week), color = "grey", data = df_grey) +
    geom_point(aes(y = water_potential, x = lwc, shape = time, color = "df_1"), 
               data = df_1 ) +
    geom_line(aes(y = water_potential, x = lwc, group = tree_week, color = "df_1"), 
              data = df_1) +
    geom_point(aes(y = water_potential, x = lwc, shape = time, color = "df_2"), 
               data = df_2) +
    geom_line(aes(y = water_potential, x = lwc, group = tree_week, color = "df_2"), 
              data = df_2) +
    geom_point(aes(y = water_potential, x = lwc, shape = time, color = "df_4"), 
               data = df_4) +
    geom_line(aes(y = water_potential, x = lwc, group = tree_week, color = "df_4"), 
              data = df_4
              ) +
    scale_colour_manual(name = 'Week', 
        values =c("df_1" ="#48578E",
                   "df_2"="#8E9D30",
                  # "df_3"="#EC7E28",
                   "df_4"= "#E97B6E"
                   ), 
         labels = c('10',
                    '17',
                  #  '21',
                    '33')) +
    labs(y = "Water Potential (MPa)", 
         #y = " ",
       x = "Leaf Water Content (g)", 
       color= "Week", 
       shape = "Time"
       #caption = "triangles = predawn, circles = midday"
       ) +
   theme(
  strip.background = element_blank(),
  strip.text.y = element_blank(), 
  strip.text.x = element_text(size = 20), 
  axis.text.y = element_text(size = 18), 
  axis.text.x = element_text(size = 18), 
  #axis.ticks.y = element_blank(), 
  axis.title.x = element_blank(),
  axis.title.y = element_blank(),
  legend.title = element_text(size = 18), 
  legend.position = "none"
  ) +
   ylim(-5,0)+
   xlim(.5,2) +
  scale_x_reverse() +
scale_y_continuous(labels = scales::number_format(accuracy = 0.1))
nice_hydration_layered_nolabs
```
#####Space, labels: 

```{r, warning = F, echo=FALSE}
#scaled
space_nice_ESA <- wc_wk_centered_df %>% 
  drop_na(site) %>% 
  ggplot(aes(y = water_potential, 
            # x = lwc_centered, 
            x = lwc,
             #color = tree_factor
             color = as.factor(week)
             )) +
  geom_point(alpha = .5, 
            # aes (shape = site)
             ) +
     theme(legend.position="none",
       # legend.position= c(.7, .2),
      strip.background = element_blank(),
      strip.text.x = element_text(size = 18),
      plot.title = element_text(size=13),
     # axis.title = element_text(size = 16),
     axis.text = element_text(size = 18),
     legend.key=element_blank(), 
      axis.title.x = element_text(size = 20), 
     axis.title.y = element_text(size = 20), 
     legend.text = element_text(size = 13), 
     legend.title = element_text(size = 16),
     #legend.margin=margin(0,0,0,0),
     # legend.box.margin=margin(-5,-8,-8,-8)
    ) +
  geom_smooth(method = "lm", se = F) + 
 # geom_vline(xintercept = 0, linetype = "dotted") +
  labs(y= "Midday WP (MPa)", 
       x = "Leaf Water Content (g wet/g dry)", 
       color = "Week", 
       shape = "Site") +
  color_many_2 +
  #scale_x_reverse() +
  #color_week_all +
  guides(color = guide_legend(nrow = 1)) +
scale_y_continuous(labels = scales::number_format(accuracy = 0.1))
space_nice_ESA
```
####Space, nolabs: 

```{r}
#scaled
space_nice_nolabs <- wc_wk_centered_df %>% 
  drop_na(site) %>% 
  ggplot(aes(y = water_potential, 
            # x = lwc_centered, 
            x = lwc,
             #color = tree_factor
             color = as.factor(week)
             )) +
  geom_point(alpha = .5, 
            # aes (shape = site)
             ) +
  theme(
  strip.background = element_blank(),
  strip.text.y = element_blank(), 
  strip.text.x = element_text(size = 20), 
  axis.text.y = element_text(size = 18), 
  axis.text.x = element_text(size = 18), 
  #axis.ticks.y = element_blank(), 
  axis.title.x = element_blank(),
  axis.title.y = element_blank(),
  legend.title = element_text(size = 18), 
  legend.position = "none"
  ) +
  geom_smooth(method = "lm", se = F,size = .5) + 
 # geom_vline(xintercept = 0, linetype = "dotted") +
  labs(#y= "Middays (MPa)", 
       y = " ",
       x = "Leaf Water Content", 
       color = "Week", 
       shape = "Site") +
  color_many_2 +
  xlim(.5,2) +
  ylim(-5,0)+
  guides(color = guide_legend(nrow = 2)) +
 # scale_x_reverse() +
scale_y_continuous(labels = scales::number_format(accuracy = 0.1))
space_nice_nolabs
```
#####Centered space, labs: 

```{r, warning = F, echo=FALSE, fig.height=4, fig.width=6}
#scaled
space_nice_centered_labs <- wc_wk_centered_df %>% 
  drop_na(site) %>% 
  ggplot(aes(y = water_potential, 
             x = lwc_centered, 
            #x = lwc,
             #color = tree_factor
             color = as.factor(week)
             )) +
  geom_point(alpha = .5, 
            # aes (shape = site)
             ) +
    theme(legend.position="none",
          #legend.position="top",
       # legend.position= c(.7, .2),
      strip.background = element_blank(),
      strip.text.x = element_text(size = 18),
      plot.title = element_text(size=13),
     # axis.title = element_text(size = 16),
     axis.text = element_text(size = 18),
     legend.key=element_blank(), 
      axis.title.x = element_text(size = 20), 
     axis.title.y = element_text(size = 20), 
     legend.text = element_text(size = 13), 
     legend.title = element_text(size = 16),
     #legend.margin=margin(0,0,0,0),
     # legend.box.margin=margin(-5,-8,-8,-8)
    ) +
  geom_smooth(method = "lm", se = F) + 
 # geom_vline(xintercept = 0, linetype = "dotted") +
  labs(y= "Middays (MPa)", 
       x = "Centered Leaf Water Content", 
       color = "Week", 
       shape = "Site") +
  color_week_assigned +
  # ggpubr::stat_regline_equation(label.x = -.75, label.y = c(1.2, .6, .2, -.2, -.6, -1.0, -1.4,  -1.8,  -2.2,  -2.6, -3.0),
  #                               position_jitter = TRUE,
  #                               aes(label =  paste(..adj.rr.label.., sep = "~~~~~~~"))) +
  #color_week_all +
  guides(color = guide_legend(nrow = 1))


space_nice_centered_labs

ggsave(here("figures", "nice_space_centered_ESA"), space_nice_centered_ESA, device = "jpg", width = 6, height = 4, dpi = 300)
```

#####Centered space, nolabs:  

```{r, warning = F, echo=FALSE}
#scaled
space_nice_centered_nolabs <- wc_wk_centered_df %>% 
  drop_na(site) %>% 
  ggplot(aes(y = water_potential, 
             x = lwc_centered, 
            #x = lwc,
             #color = tree_factor
             color = as.factor(week)
             )) +
  geom_point(alpha = .5, 
            # aes (shape = site)
             ) +
  theme(
  strip.background = element_blank(),
  strip.text.y = element_blank(), 
  strip.text.x = element_text(size = 20), 
  axis.text.y = element_text(size = 18), 
  axis.text.x = element_text(size = 18), 
  #axis.ticks.y = element_blank(), 
  axis.title.x = element_blank(),
  axis.title.y = element_blank(),
  legend.title = element_text(size = 18), 
  legend.position = "none"
  ) +
  geom_smooth(method = "lm", se = F) + 
 # geom_vline(xintercept = 0, linetype = "dotted") +
  labs(y= "Middays (MPa)", 
       x = "Centered Leaf Water Content", 
       color = "Week", 
       shape = "Site") +
  color_week_assigned +
  #color_week_all +
  guides(color = guide_legend(nrow = 1))


space_nice_centered_nolabs
```

#####Time, labs:

```{r}
time_ESA <- wc_qudo_df %>% 
  mutate(time = case_when(
    time == "md" ~ "Midday", 
    time == "pd" ~ "Predawn"
  )) %>% 
  filter(time == "Midday") %>% 
  drop_na(week) %>% 
 # filter(time == "md") %>% 
  ggplot(aes(y = water_potential, 
             x = lwc, 
             color = time_season, 
             size = week,
             shape = as.factor(tree),
             show.legend = FALSE)) +
  geom_point(size = 1,
             alpha = .1)+
  geom_smooth(method = "lm", se = F, size = .5, alpha = .4) +
 # theme(legend.position = "none") +
  labs(x = "LWC", 
       y = "Midday MPa") +
  #color_two_grey +
  # theme(
  #     legend.position="none",
  #     strip.background = element_blank(),
  #    # strip.text.x = element_text(size = 18),
  #     strip.text.x = element_text(size = 18),
  #     plot.title = element_text(size=13),
  #     #axis.title = element_text(size = 15),
  #    axis.title = element_blank(),
  #    axis.text = element_text(size = 18),
  #    axis.text.x = element_text(size = 18),
  #    legend.key=element_blank(), 
  #    legend.text = element_text(size = 13), 
  #    legend.title = element_text(size = 16),
  #    #legend.title = element_blank(),
  #    legend.margin=margin(0,0,0,0),
  #     legend.box.margin=margin(-5,-8,-8,-8)
  #   ) +
    theme(legend.position="none",
       # legend.position= c(.7, .2),
      strip.background = element_blank(),
      strip.text.x = element_text(size = 18),
      plot.title = element_text(size=13),
     # axis.title = element_text(size = 16),
     axis.text = element_text(size = 18),
     legend.key=element_blank(), 
      axis.title.x = element_text(size = 20), 
     axis.title.y = element_text(size = 20), 
     legend.text = element_text(size = 13), 
     legend.title = element_text(size = 16),
     #legend.margin=margin(0,0,0,0),
     # legend.box.margin=margin(-5,-8,-8,-8)
    ) +
  labs(#y= "Water Potential (MPa)", 
       y = "Water Potential (MPa)",
       x = "Leaf Water Content (g)", 
       color = "Week", 
       ) +
  guides(color = guide_legend(nrow = 2)) +
 # facet_wrap(~time, nrow = 2) +
   xlim(.5,2) +
  ylim(-5,0)+
 # scale_x_reverse()+
  color_two_grey+
scale_y_continuous(labels = scales::number_format(accuracy = 0.1))

time_ESA
```

#####Time, nolabs: 

```{r}
time_nolabs <- wc_qudo_df %>% 
  mutate(time = case_when(
    time == "md" ~ "Midday", 
    time == "pd" ~ "Predawn"
  )) %>% 
  filter(time == "Midday") %>% 
  drop_na(week) %>% 
 # filter(time == "md") %>% 
  ggplot(aes(y = water_potential, 
             x = lwc, 
             color = time_season, 
             size = week,
             shape = as.factor(tree),
             show.legend = FALSE)) +
  geom_point(size = 1,
             alpha = .1)+
  geom_smooth(method = "lm", se = F, size = .5, alpha = .4) +
 # theme(legend.position = "none") +
  labs(x = "LWC", 
       y = "Midday MPa") +
  theme(
  strip.background = element_blank(),
  strip.text.y = element_blank(), 
  strip.text.x = element_text(size = 20), 
  axis.text.y = element_text(size = 18), 
  axis.text.x = element_text(size = 18), 
  #axis.ticks.y = element_blank(), 
  axis.title.x = element_blank(),
  axis.title.y = element_blank(),
  legend.title = element_text(size = 18), 
  legend.position = "none"
  ) +
  labs(#y= "Water Potential (MPa)", 
       y = "Water Potential (MPa)",
       x = "Leaf Water Content (g)", 
       color = "Week", 
       ) +
  guides(color = guide_legend(nrow = 2)) +
 # facet_wrap(~time, nrow = 2) +
   xlim(.5,2) +
  ylim(-5,0)+
  scale_x_reverse()+
  color_two_grey+
scale_y_continuous(labels = scales::number_format(accuracy = 0.1))

time_nolabs
```




#Slopes: 

####Hydration, labels: 

```{r, echo=FALSE, fig.height=5, fig.width=9}
hyd_slopes_labs <- ran_df_week_hyd %>% 
  filter(!week %in% c(9)) %>% 
 # filter(week %in% c(14, 17, 21, 29)) %>% 
 # filter(term == "lwc") %>% 
  mutate(upr = slope + (std.error.slope), 
         lwr = slope - (std.error.slope)) %>% 
  ggplot(aes(color= as.character(week))
    ) + 
  geom_point(aes(y = slope, x = week), size =4) +
  geom_point(aes(y = upr, x = week), size = 2) +
  geom_point(aes(y = lwr, x = week), size = 2) +
  #geom_line(aes(group = week, y = week, x = upr)) +
  geom_segment(aes(y= lwr, 
                   yend = upr, 
                   x = week, 
                   xend = week, 
                   color = as.character(week)))+
  labs(x = "Week", 
       color = "Week", 
       y = "Slope (MPa ~ LWC)") +
   # facet_wrap(~y_var_name, scales = "free") + 
  theme(
  strip.background = element_blank(),
  strip.text.y = element_blank(), 
  strip.text.x = element_text(size = 20), 
  axis.text.y = element_text(size = 16), 
  axis.text.x = element_text(size = 16), 
  #axis.ticks.y = element_blank(), 
  axis.title.x = element_text(size = 20), 
  axis.title.y = element_text(size = 20), 
  legend.title = element_text(size = 18), 
  legend.position = "none"
  ) +
  geom_hline(yintercept = 0, linetype="dotted") + 
  scale_x_continuous(breaks = c(10, 14,15, 17, 18, 19, 21, 29, 33, 37)
                      # seq(10, 30, by = 1)
                     ) +
  theme(legend.position = "none") +
  #xlim(0, 40) +
  scale_color_manual(values = c("9" =  "grey", 
                                                     "10" = "#48578E",
                                                     "11" = "grey", 
                                                     "12" = "grey", 
                                                     "14" = "grey",  
                                                     "15" = "grey", 
                                                     "16" = "grey", 
                                                     "17" = "#8E9D30",
                                                     "18" = "grey",  
                                                     "19" = "grey", 
                                                     "21" = "grey", 
                                                     "20" = "grey",  
                                                     "29" = "grey", 
                                                     "33" = "#CC5210", 
                                                     "37" = "grey", 
                                                     "39" = "grey")) +
   ylim(-1, 10) 
hyd_slopes_labs
```

####Hydration, no labels: 

```{r, echo=FALSE}
hyd_slopes_nolabs <- ran_df_week %>% 
  filter(!week %in% c(9)) %>% 
 # filter(week %in% c(14, 17, 21, 29)) %>% 
 # filter(term == "lwc") %>% 
  mutate(upr = slope + (std.error.slope), 
         lwr = slope - (std.error.slope)) %>% 
  ggplot(aes(color= as.character(week))
    ) + 
  geom_point(aes(y = slope ,x = week), size =4) +
    geom_point(aes(y = upr, x = week), size = 2) +
  geom_point(aes(y = lwr, x = week), size = 2) +
  #geom_line(aes(group = week, y = week, x = upr)) +
  geom_segment(aes(y= lwr, 
                   yend = upr, 
                   x = week, 
                   xend = week, 
                   color = as.character(week)))+
  labs(#x = "Week", 
       color = "week", 
       y = "Slope (MPa ~ LWC)") +
   # facet_wrap(~y_var_name, scales = "free") + 
  theme(
  strip.background = element_blank(),
  strip.text.y = element_blank(), 
  strip.text.x = element_text(size = 20), 
  axis.text.y = element_text(size = 18), 
  axis.text.x = element_text(size = 12), 
  #axis.ticks.y = element_blank(), 
  axis.title.x = element_blank(),
  axis.title.y = element_blank(),
  legend.title = element_text(size = 18), 
  legend.position = "none"
  ) +
  geom_hline(yintercept = 0, linetype="dotted") + 
  scale_x_continuous(breaks = c(10, 14,15, 17, 18, 19, 21, 29, 33, 37)
                      # seq(10, 30, by = 1)
                     ) +
  theme(legend.position = "none") +
  #xlim(0, 40) +
  scale_color_manual(values = c("9" =  "grey", 
                                                     "10" = "#48578E",
                                                     "11" = "grey", 
                                                     "12" = "grey", 
                                                     "14" = "grey",  
                                                     "15" = "grey", 
                                                     "16" = "grey", 
                                                     "17" = "#8E9D30",
                                                     "18" = "grey",  
                                                     "19" = "grey", 
                                                     "21" = "grey", 
                                                     "20" = "grey",  
                                                     "29" = "grey", 
                                                     "33" = "#CC5210", 
                                                     "37" = "grey", 
                                                     "39" = "grey")) +
   ylim(-1, 10) 
hyd_slopes_nolabs
```


####Space, labels: 

```{r, echo=FALSE}
space_slopes_labs <- ran_df_week_3 %>% 
  filter(!week %in% c(9)) %>% 
 # filter(week %in% c(14, 17, 21, 29)) %>% 
 # filter(term == "lwc") %>% 
  mutate(upr = slope + (std.error.slope), 
         lwr = slope - (std.error.slope)) %>% 
  ggplot(aes(color= as.character(week))
    ) + 
  geom_point(aes(y = slope ,x = week), size =4) +
  geom_point(aes(y = upr, x = week), size = 2) +
  geom_point(aes(y = lwr, x = week), size = 2) +
  #geom_line(aes(group = week, y = week, x = upr)) +
  geom_segment(aes(y= lwr, 
                   yend = upr, 
                   x = week, 
                   xend = week, 
                   color = as.character(week)))+
  labs(x = "Week", 
       color = "week", 
       y = "Slope (MPa ~ LWC)") +
   # facet_wrap(~y_var_name, scales = "free") + 
  theme(
  strip.background = element_blank(),
  strip.text.y = element_blank(), 
  strip.text.x = element_text(size = 20), 
  axis.text.y = element_text(size = 18), 
  axis.text.x = element_text(size = 18), 
  #axis.ticks.y = element_blank(), 
  axis.title.x = element_blank(),
  axis.title.y = element_text(size = 20), 
  legend.title = element_text(size = 18), 
  legend.position = "none"
  ) +
  geom_hline(yintercept = 0, linetype="dotted") + 
  scale_x_continuous(breaks = c(10,  14,15,17, 19, 21, 29, 33, 37)
                      # seq(10, 30, by = 1)
                     ) +
  theme(legend.position = "none") +
   ylim(-.25, 5)  +
  color_week_assigned

space_slopes_labs
```
####Space, no labs: 

```{r, echo=FALSE}
space_slopes_nolabs <- ran_df_week_3 %>% 
  filter(!week %in% c(9)) %>% 
 # filter(week %in% c(14, 17, 21, 29)) %>% 
 # filter(term == "lwc") %>% 
  mutate(upr = slope + (std.error.slope), 
         lwr = slope - (std.error.slope)) %>% 
  ggplot(aes(color= as.character(week))
    ) + 
  geom_point(aes(y = slope ,x = week), size =4) +
  geom_point(aes(y = upr, x = week), size = 2) +
  geom_point(aes(y = lwr, x = week), size = 2) +
  #geom_line(aes(group = week, y = week, x = upr)) +
  geom_segment(aes(y= lwr, 
                   yend = upr, 
                   x = week, 
                   xend = week, 
                   color = as.character(week)))+
  labs(x = "Week", 
       color = "week", 
       y = "Slope (MPa ~ LWC)") +
   # facet_wrap(~y_var_name, scales = "free") + 
  theme(
  strip.background = element_blank(),
  strip.text.y = element_blank(), 
  strip.text.x = element_text(size = 20), 
  axis.text.y = element_text(size = 18), 
  axis.text.x = element_text(size = 12), 
  #axis.ticks.y = element_blank(), 
  axis.title.x = element_blank(),
  axis.title.y = element_blank(),
  legend.title = element_text(size = 18), 
  legend.position = "none"
  ) +
  geom_hline(yintercept = 0, linetype="dotted") + 
  scale_x_continuous(breaks = c(10, 14,15, 17, 19, 21, 29, 33, 37)
                      # seq(10, 30, by = 1)
                     ) +
  theme(legend.position = "none") +
  color_week_assigned +
   ylim(-1, 10) 

space_slopes_nolabs
```

####Time, labs

```{r, fig.height=6, fig.width=5}
#Time
ran_df_tree_before_vs_after <- bind_rows(bef_ran_df_tree_before, lin_ran_df_tree_after)

ef <- ran_df_tree_before_vs_after %>% 
  group_by(time_season) %>% 
  mutate(sd = sd(slope),
         slope = mean(slope), 
         mean_se = mean(std.error.slope),
        mean_std.error = mean(std.error),
        upr_sd = slope + mean_std.error,
        lwr_sd = slope - mean_std.error,
         upr = slope + mean_se,
         lwr = slope - mean_se,
         time_season = as.factor(time_season)) 
# %>% 
#   select(slope, upr, lwr, time_season, sd)

time_slope_labs <- ef %>% 
  # mutate(slope = -1 * slope, 
  #        upr = -1*upr, 
  #        lwr = -1*lwr) %>% 
ggplot(aes(color = time_season)) + 
  geom_point(aes(y = slope, x = time_season), size =4) +
    geom_point(aes(y = upr, x = time_season), size = 1) +
  geom_point(aes(y = lwr, x = time_season), size = 1) +
  #geom_line(aes(group = tree, y = tree, x = upr)) +
  geom_segment(aes(y= lwr, 
                   yend = upr, 
                   x = time_season, 
                   xend = time_season)) +
  # scale_x_discrete(limits = c("Before Leafout", "After Leafout"),
  #                  labels = c("Before Leafout", "After Leafout")) +
  labs(#y = "Mean Slope +/- SD acrss all trees
                 #for each time frame", 
   y = "Slope (MPa ~ LWC)",
       x = "Time") +
  color_two_grey +
  geom_hline(yintercept = 0, linetype="dotted") + 
  theme(
  strip.background = element_blank(),
  strip.text.y = element_blank(), 
  strip.text.x = element_text(size = 20), 
  axis.text.y = element_text(size = 18), 
  axis.text.x = element_text(size = 18), 
  #axis.ticks.y = element_blank(), 
  axis.title.x = element_blank(),
  axis.title.y = element_text(size = 18), 
  legend.title = element_text(size = 18), 
  legend.position = "none"
  ) +
  # theme(legend.position="none",
  #     strip.background = element_blank(),
  #     strip.text.x = element_text(size = 18),
  #     plot.title = element_text(size=13),
  #     axis.title.y = element_text(size = 15),
  #     #axis.title.x = element_text(size = 13),
  #     axis.title.x = element_blank(),
  #    axis.text = element_text(size = 18),
  #    legend.key=element_blank(), 
  #    legend.text = element_text(size = 13), 
  #    legend.title = element_text(size = 16),
  #    legend.margin=margin(0,0,0,0),
  #     legend.box.margin=margin(-5,-8,-8,-8)
  #   ) +
 # ylim(-1, 4)  +
  scale_x_discrete(limits=rev) 
  
  
  
time_slope_labs

```

####Time, no labs
```{r}
#Time
ran_df_tree_before_vs_after <- bind_rows(bef_ran_df_tree_before, lin_ran_df_tree_after)

ef <- ran_df_tree_before_vs_after %>% 
  group_by(time_season) %>% 
  mutate(sd = sd(slope),
         slope = mean(slope), 
         mean_se = mean(std.error.slope),
        mean_std.error = mean(std.error),
        upr_sd = slope + mean_std.error,
        lwr_sd = slope - mean_std.error,
         upr = slope + mean_se,
         lwr = slope - mean_se,
         time_season = as.factor(time_season)) 
# %>% 
#   select(slope, upr, lwr, time_season, sd)

time_slopes_nolabs <- ef %>% 
ggplot(aes(color = time_season)) + 
  geom_point(aes(y = slope, x = time_season), size =4) +
    geom_point(aes(y = upr, x = time_season), size = 1) +
  geom_point(aes(y = lwr, x = time_season), size = 1) +
  #geom_line(aes(group = tree, y = tree, x = upr)) +
  geom_segment(aes(y= lwr, 
                   yend = upr, 
                   x = time_season, 
                   xend = time_season)) +
  # scale_x_discrete(limits = c("Before Leafout", "After Leafout"),
  #                  labels = c("Before Leafout", "After Leafout")) +
  labs(#y = "Mean Slope +/- SD acrss all trees
                 #for each time frame", 
   y = "",
       x = "Time") +
  color_two_grey +
  geom_hline(yintercept = 0, linetype="dotted") + 
  theme(
  strip.background = element_blank(),
  strip.text.y = element_blank(), 
  strip.text.x = element_text(size = 20), 
 axis.text.y = element_text(size = 18), 
  axis.text.x = element_text(size = 18), 
  #axis.ticks.y = element_blank(), 
  axis.title.x = element_blank(),
  axis.title.y = element_blank(), 
  legend.title = element_text(size = 18), 
 
 legend.position = "none"
  ) +
  # theme(legend.position="none",
  #     strip.background = element_blank(),
  #     strip.text.x = element_text(size = 18),
  #     plot.title = element_text(size=13),
  #     axis.title.y = element_text(size = 15),
  #     #axis.title.x = element_text(size = 13),
  #     axis.title.x = element_blank(),
  #    axis.text = element_text(size = 18),
  #    legend.key=element_blank(), 
  #    legend.text = element_text(size = 13), 
  #    legend.title = element_text(size = 16),
  #    legend.margin=margin(0,0,0,0),
  #     legend.box.margin=margin(-5,-8,-8,-8)
  #   ) +
  ylim(-1, 10)  +
  scale_x_discrete(limits=rev) 
  
  
time_slopes_nolabs
```

##COMBINE:

```{r}
legend_plot <- wc_wk_centered_df %>% 
  drop_na(site) %>% 
  ggplot(aes(y = water_potential,
            x = lwc,
             color = as.character(week)
             )) +
  geom_point(alpha = 1) +
  theme(legend.position="top",
       # legend.position= c(.7, .2),
      strip.background = element_blank(),
      strip.text.x = element_text(size = 18),
      plot.title = element_text(size=13),
     # axis.title = element_text(size = 16),
     axis.text = element_text(size = 18),
     legend.key=element_blank(), 
     axis.title.x = element_blank(),
     axis.title.y = element_blank(),
     legend.text = element_text(size = 13), 
     legend.title = element_text(size = 16),
     legend.margin=margin(0,0,0,0),
    legend.box.margin=margin(-5,-8,-8,-8)
    ) +
  geom_smooth(method = "lm", se = F, size = .5) + 
  labs(color = "Week") +
  color_week_assigned +
 # ylim(0,2) +
  guides(color = guide_legend(nrow = 1))
legend_plot

legend_scatterplots <- cowplot::get_legend(legend_plot)
legend_scatterplots
```

```{r}
y.grob1 <- textGrob("Slope", 
                   gp=gpar(fontface="bold", #col="blue", 
                           fontsize=24), rot=90)

x.grob1 <- textGrob("Time", 
                   gp=gpar(fontface="bold", #col="blue", 
                           fontsize=24))


combined_slopes_wide <- cowplot::plot_grid(space_slopes_nolabs, time_slopes_nolabs, hyd_slopes_nolabs, 
                                   nrow = 1, rel_heights = c(.15, 1, .3), 
                                   rel_widths = c(1, 1, 1)
                                   ) 

combined_slopes_wide

combined_slopes_wide_labels <- grid.arrange(arrangeGrob(combined_slopes_wide, left = y.grob1, bottom = x.grob1))

y.grob2 <- textGrob("Water Potential (MPa)", 
                   gp=gpar(fontface="bold", #col="blue", 
                           fontsize=24), rot=90)

x.grob2 <- textGrob("Leaf Water Content (g)", 
                   gp=gpar(fontface="bold", #col="blue",
                           fontsize=24))


combined_plots_wide_nolegend <- cowplot::plot_grid(space_nice_centered_nolabs, time_nolabs, nice_hydration_layered_nolabs,
                                   nrow = 1, rel_heights = c(.15, 1, .3), 
                                   rel_widths = c(1, 1, 1)
                                   ) 
combined_plots_wide_nolegend

combined_plots_wide <- cowplot::plot_grid(legend_scatterplots, combined_plots_wide_nolegend,
                                          nrow = 2, rel_heights = c(.25, 1))

combined_plots_wide_labels <- grid.arrange(arrangeGrob(combined_plots_wide, left = y.grob2, bottom = x.grob2))

combined_plots_all <- cowplot::plot_grid(combined_plots_wide_labels, combined_slopes_wide_labels, 
                                         nrow = 2)
combined_plots_all

ggsave(here("figures", "combined_plots_all"), combined_plots_all, device = "jpg", width = 18, height = 10, dpi = 300)
```
#CWC: 

##Scatterplots:

####Time: 
```{r, warning = F}
time_cwc_df <- cwc_df %>% 
  mutate(time_season = case_when(
    week < 17 ~ "Before Leafout", 
    week >= 18 ~ "After Leafout", 
    TRUE ~ as.character(week)
  ))

time_cwc <- time_cwc_df %>% 
  drop_na(week) %>% 
  filter(time == "md") %>% 
  ggplot(aes(y = water_potential, 
             x = cwc, 
             color = time_season, 
             size = week,
             shape = as.factor(tree),
             show.legend = FALSE)) +
  geom_point(size = 1,
             alpha = .3)+
  geom_smooth(method = "lm", se = F) +
 # theme(legend.position = "none") +
  labs(x = "cwc", 
       y = "Midday MPa") +
  #color_two_grey +
  theme(#legend.position="none",
        legend.position="none",
       # legend.position= c(.7, .2),
      strip.background = element_blank(),
      strip.text.x = element_text(size = 18),
      plot.title = element_text(size=13),
     # axis.title = element_text(size = 16),
     axis.text = element_text(size = 18),
     legend.key=element_blank(), 
      axis.title.x = element_text(size = 20),
     axis.title.y = element_text(size = 20), 
     legend.text = element_text(size = 13), 
     legend.title = element_text(size = 16),
     legend.margin=margin(0,0,0,0),
      legend.box.margin=margin(-5,-8,-8,-8)
    ) +
  geom_smooth(method = "lm", se = F) + 
 # geom_vline(xintercept = 0, linetype = "dotted") +
  labs(y= "Middays (MPa)", 
       x = "Canopy Water Content (g/cm2)", 
       color = "Week", 
       ) +
  guides(color = guide_legend(nrow = 2)) +
 # facet_wrap(~time, nrow = 2) +
  color_two_grey 
 # scale_x_reverse()
time_cwc 

ggsave(here("figures", "nice_time_cwc"), time_cwc, device = "jpg", width = 4, height = 2, dpi = 300)
```

####Space: 

```{r}
wc_wk_centered_df_cwc <- wk_all_long %>% 
  #filter(!week %in% c(9)) %>% 
  mutate(water_potential = water_potential) %>% 
  filter(time == "md") %>% 
  group_by(week) %>% 
  mutate(mean_cwc = mean(cwc, na.rm = T)) %>% 
  ungroup() %>% 
  mutate(cwc_centered = cwc - mean_cwc)
  # mutate(cwc_centered = scale(cwc,  scale=FALSE)) %>% 
  # filter(cwc_centered < 4)

#scaled
space_nice_cwc <- wc_wk_centered_df_cwc%>% 
  #drop_na(site) %>% 
  ggplot(aes(y = water_potential, 
            # x = cwc_centered, 
            x = cwc_centered,
             #color = tree_factor
             color = as.factor(week)
             )) +
  geom_point(#alpha = .5, 
            # aes (shape = site)
             ) +
  theme(#legend.position="none",
        legend.position="none",
       # legend.position= c(.7, .2),
      strip.background = element_blank(),
      strip.text.x = element_text(size = 18),
      plot.title = element_text(size=13),
     # axis.title = element_text(size = 16),
     axis.text = element_text(size = 18),
     legend.key=element_blank(), 
      axis.title.x = element_text(size = 20),
     axis.title.y = element_text(size = 20), 
     legend.text = element_text(size = 13), 
     legend.title = element_text(size = 16),
     legend.margin=margin(0,0,0,0),
      legend.box.margin=margin(-5,-8,-8,-8)
    ) +
  geom_smooth(method = "lm", se = F) + 
 # geom_vline(xintercept = 0, linetype = "dotted") +
  labs(y= "Middays (MPa)", 
       x = "Canopy Water Content (centered)", 
       color = "Week") +
  color_week_assigned +
  geom_vline(xintercept = 0, linetype="dotted") + 
  #color_week_all +
  guides(color = guide_legend(nrow = 1)) #+
 # scale_x_reverse()
  
space_nice_cwc

ggsave(here("figures", "nice_space_cwc"), space_nice_cwc, device = "jpg", width = 6, height = 4, dpi = 300)
```

##Slopes: 

####Time: 

```{r, warning=F}
#After: 
lin_wc_qudo_md_df <- time_cwc_df %>% 
  filter(time == "md") %>% 
  filter(week > 17) %>% 
  drop_na(site)
  
  
lin_time_mod <- lmer(water_potential ~ cwc + (1|week) + (cwc|tree) + (1|site), data = lin_wc_qudo_md_df)
summary(lin_time_mod)

lin_ran_list <- coef(lin_time_mod)
lin_ran_list

lin_tree_eff <- as.data.frame(lin_ran_list[['tree']]) %>% 
  mutate(estimate = `(Intercept)`, 
         slope = `cwc`,
         sd = sd(slope)
         ) %>%
  select(-`(Intercept)`, 
          -cwc)
lin_tree_eff

lin_ran_err_tree <- arm::se.ranef(lin_time_mod)

lin_ran_err_tree <- as.data.frame(lin_ran_err_tree[['tree']]) %>% 
  mutate(std.error = `(Intercept)`, 
         std.error.slope = `cwc`
         )%>% 
  select(-`(Intercept)`, 
        # -cwc
         ) %>% 
  tibble::rownames_to_column("tree") # Apply rownames_to_column

lin_ran_df_tree_after <- bind_cols(lin_tree_eff, lin_ran_err_tree) %>% 
  #select(-`1:47`) %>% 
  data_frame() %>% 
  mutate(time_season = "After Leafout")

##Before: 
bef_wc_qudo_md_df <- cwc_df %>% 
  filter(time == "md") %>% 
  filter(week < 17) %>% 
  drop_na(site)
  
  
bef_time_mod <- lmer(water_potential ~ cwc + (1|week) + (cwc|tree) + (1|site), data = bef_wc_qudo_md_df, REML = T)
summary(bef_time_mod)

bef_ran_list <- coef(bef_time_mod)

bef_tree_eff <- as.data.frame(bef_ran_list[['tree']]) %>% 
  mutate(estimate = `(Intercept)`, 
         slope = `cwc`, 
         sd = sd(slope)
         ) %>%
  select(-`(Intercept)`, 
          -cwc)
bef_tree_eff

bef_ran_err_tree <- arm::se.ranef(bef_time_mod)

bef_ran_err_tree <- as.data.frame(bef_ran_err_tree[['tree']]) %>% 
  mutate(std.error = `(Intercept)`, 
         std.error.slope = `cwc`
         )%>% 
  select(-`(Intercept)`, 
         -cwc
         ) %>% 
  tibble::rownames_to_column("tree") # Apply rownames_to_column

bef_ran_df_tree_before <- bind_cols(bef_tree_eff, bef_ran_err_tree) %>% 
  #select(-`1:47`) %>% 
  data_frame()%>% 
  mutate(time_season = "Before Leafout")

#Time
ran_df_tree_before_vs_after <- bind_rows(bef_ran_df_tree_before, lin_ran_df_tree_after)

ef <- ran_df_tree_before_vs_after %>% 
  group_by(time_season) %>% 
  mutate(sd = sd(slope),
         slope = mean(slope), 
         mean_se = mean(std.error.slope),
        mean_std.error = mean(std.error),
        upr_sd = slope + mean_std.error,
        lwr_sd = slope - mean_std.error,
         upr = slope + mean_se,
         lwr = slope - mean_se,
         time_season = as.factor(time_season)) 
# %>% 
#   select(slope, upr, lwr, time_season, sd)

time_slope_labs <- ef %>% 
ggplot(aes(color = time_season)) + 
  geom_point(aes(y = slope, x = time_season), size =4) +
    geom_point(aes(y = upr, x = time_season), size = 1) +
  geom_point(aes(y = lwr, x = time_season), size = 1) +
  #geom_line(aes(group = tree, y = tree, x = upr)) +
  geom_segment(aes(y= lwr, 
                   yend = upr, 
                   x = time_season, 
                   xend = time_season)) +
  # scale_x_discrete(limits = c("Before Leafout", "After Leafout"),
  #                  labels = c("Before Leafout", "After Leafout")) +
  labs(#y = "Mean Slope +/- SD acrss all trees
                 #for each time frame", 
   y = "",
       x = "Time") +
  color_two_grey +
  geom_hline(yintercept = 0, linetype="dotted") + 
  theme(
  strip.background = element_blank(),
  strip.text.y = element_blank(), 
  strip.text.x = element_text(size = 20), 
  axis.text.y = element_text(size = 18), 
  axis.text.x = element_text(size = 18), 
  #axis.ticks.y = element_blank(), 
  axis.title.x = element_blank(),
  axis.title.y = element_text(size = 20), 
  legend.title = element_text(size = 18), 
  legend.position = "none"
  ) +
  # theme(legend.position="none",
  #     strip.background = element_blank(),
  #     strip.text.x = element_text(size = 18),
  #     plot.title = element_text(size=13),
  #     axis.title.y = element_text(size = 15),
  #     #axis.title.x = element_text(size = 13),
  #     axis.title.x = element_blank(),
  #    axis.text = element_text(size = 18),
  #    legend.key=element_blank(), 
  #    legend.text = element_text(size = 13), 
  #    legend.title = element_text(size = 16),
  #    legend.margin=margin(0,0,0,0),
  #     legend.box.margin=margin(-5,-8,-8,-8)
  #   ) +
 # ylim(-1, 4)  +
  scale_x_discrete(limits=rev) 
  
  
time_slope_labs
```

```{r, fig.height=6, fig.width=5}
time_slope_labs <- ef %>% 
ggplot(aes(color = time_season)) + 
  geom_hline(yintercept = 0, linetype="dotted") + 
  geom_point(aes(y = slope, x = time_season), size =4) +
    geom_point(aes(y = upr, x = time_season), size = 1) +
  geom_point(aes(y = lwr, x = time_season), size = 1) +
  #geom_line(aes(group = tree, y = tree, x = upr)) +
  geom_segment(aes(y= lwr, 
                   yend = upr, 
                   x = time_season, 
                   xend = time_season)) +
  # scale_x_discrete(limits = c("Before Leafout", "After Leafout"),
  #                  labels = c("Before Leafout", "After Leafout")) +
  labs(#y = "Mean Slope +/- SD acrss all trees
                 #for each time frame", 
   y = "Slope (MPa ~ CWC)",
       x = "Time") +
  color_two_grey +
  theme(
  strip.background = element_blank(),
  strip.text.y = element_blank(), 
  strip.text.x = element_text(size = 20), 
  axis.text.y = element_text(size = 18), 
  axis.text.x = element_text(size = 18), 
  #axis.ticks.y = element_blank(), 
  axis.title.x = element_blank(),
  axis.title.y = element_text(size = 18), 
  legend.title = element_text(size = 18), 
  legend.position = "none"
  ) +
  # theme(legend.position="none",
  #     strip.background = element_blank(),
  #     strip.text.x = element_text(size = 18),
  #     plot.title = element_text(size=13),
  #     axis.title.y = element_text(size = 15),
  #     #axis.title.x = element_text(size = 13),
  #     axis.title.x = element_blank(),
  #    axis.text = element_text(size = 18),
  #    legend.key=element_blank(), 
  #    legend.text = element_text(size = 13), 
  #    legend.title = element_text(size = 16),
  #    legend.margin=margin(0,0,0,0),
  #     legend.box.margin=margin(-5,-8,-8,-8)
  #   ) +
 # ylim(-1, 4)  +
  scale_x_discrete(limits=rev) 
  
  
time_slope_labs
```

####Space: 

```{r}
space_mod_cwc <- lmer(water_potential ~ cwc_centered + (cwc_centered|week) + (1|tree), data =  wc_wk_centered_df, REML = T)

space_mod_df_cwc <- broom.mixed::tidy(space_mod_cwc)
#space_mod_df

ran_list3_cwc <- coef(space_mod_cwc)

#ran_list2 <- coef(m_wk_rand)

ran_df3_cwc <- as.data.frame(ran_list3_cwc[['week']])%>% 
  mutate(estimate = `(Intercept)`, 
         slope = `cwc_centered`, 
         -cwc_centered) %>%
  select(-`(Intercept)`)

ran_err3_cwc <- arm::se.ranef(space_mod_cwc)

ran_err_df_cwc <- as.data.frame(ran_err3_cwc[['week']]) %>% 
  mutate(std.error = `(Intercept)`, 
         std.error.slope = `cwc_centered`)%>% 
  select(-`(Intercept)`, 
         -cwc_centered) %>% 
  tibble::rownames_to_column("week") %>% 
  mutate(week = as.numeric(week))

ran_df_week_3_cwc <- bind_cols(ran_df3_cwc, ran_err_df_cwc) %>% 
  #select(-`1:10`) %>% 
  data_frame()

ran_df_week_3_cwc %>% 
 # mutate(week = as.factor(week)) %>% 
  mutate(week = as.numeric(week)) %>% 
 # filter(week %in% c(14, 17, 21, 29)) %>% 
 # filter(term == "cwc") %>% 
  mutate(upr = slope + (std.error.slope), 
         lwr = slope - (std.error.slope)) %>% 
  ggplot(aes(color= as.character(week))
    ) + 
  geom_point(aes(y = slope ,x = week), size =2) +
    geom_point(aes(y = upr, x = week), size = 1) +
  geom_point(aes(y = lwr, x = week), size = 1) +
  #geom_line(aes(group = week, y = week, x = upr)) +
  geom_segment(aes(y= lwr, 
                   yend = upr, 
                   x = week, 
                   xend = week, 
                   color = as.character(week)))+
  labs(x = "Week", 
       color = "Week", 
       y = "Slope") +
  theme(legend.position="none",
      strip.background = element_blank(),
      strip.text.x = element_text(size = 18),
      plot.title = element_text(size=13),
      axis.title = element_text(size = 16),
      axis.title.x = element_blank(),
  axis.title.y = element_text(size = 20), 
     legend.key=element_blank(), 
     legend.text = element_text(size = 13), 
     legend.title = element_text(size = 16),
     legend.margin=margin(0,0,0,0),
      legend.box.margin=margin(-5,-8,-8,-8)
    ) +
  geom_hline(yintercept = 0, linetype="dotted") + 
  scale_x_continuous(breaks = c(9, 10, 11, 12, 14,15, 16, 18, 19, 20, 21, 29, 33, 37)
                      # seq(10, 30, by = 1)
                     ) +
  color_week_assigned +
   # color_many_2 +
  guides(color = guide_legend(nrow = 1))
```


