---
title: "RWC_processing"
author: "Indra Boving"
date: "6/3/2022"
output: html_document
---

##setup

```{r setup, include=FALSE}
library(janitor)
library(here)
library(tidyverse)
library(lubridate)
library(readxl)
library(gridExtra)
library(MetBrewer)
 install.packages("data.table")
 library(data.table)
```


```{r}
## Data file version (so it's not hard coded in every read_excel() call)
datver <- "07192022"
dataversion <- paste0("Data_", datver)
```

#Field data: 

Read in water potential data:

Note: we measured Ks on stems collected on "2022-04-25" "2022-03-27" "2022-04-12" and "2022-05-23"

```{r}
####### Water Potentials 
#Date: 218 WP + LWC
rwc_df <- read_excel(here(dataversion,"WP_WC", "SHIFT data collection 2022.xlsx"), sheet="RWC DATA", skip=0, na = "NA") %>% 
  clean_names() %>% 
  mutate(date = ymd(date), 
         swc_g = wet_wt_g - dry_wt_g,
         swc_per_dry_g = (wet_wt_g - dry_wt_g)/dry_wt_g, #grams water per gram dry weight
         swc_percent = swc_per_dry_g * 100, 
         tree = tree_id, 
         year = as.character(year), 
         week = week(date), 
         swc_ww_g = wet_wt_g, 
         swc_dw_g = dry_wt_g) %>% 
  select(date, tree, swc_g, swc_per_dry_g, swc_percent, year, week, swc_ww_g, swc_dw_g, type, rep) %>% 
  mutate(timing = case_when(
    week %in% c(11, 13, 14) ~ "early", 
    week %in% c(15, 18, 19, 21) ~ "late"
  ))

dlookr::diagnose(rwc_df)
```

Take a look! 

```{r}
rwc_df %>% 
  filter(year %in% c(0,1)) %>% 
  ggplot(aes(y = swc_per_dry_g, x = date, color = as.factor(type))) +
  geom_jitter()+
  facet_wrap(~year) 
```

#Combine with water content + water potential data: 

```{r}
wc_df <- read_csv(here("processed-data", paste0("wc_alldates_",datver,".csv"))) %>% #contains LWC data
  mutate(date = lubridate::ymd(date))%>% 
  select(-...1) %>% 
  mutate(timing = case_when(
    week %in% c(9, 10, 11, 12, 13, 14) ~ "early", 
    week %in% c(15, 16, 17, 18, 19, 20, 21) ~ "late"
  ))%>% 
  mutate(date_wc = date) %>% 
  select(-date)

wp_df <- read_csv(here("processed-data", paste0("wp_alldates_",datver,".csv"))) %>% #contains WP data
  #mutate(date = lubridate::ymd(date)) %>% 
  select(-...1) %>% 
  mutate(timing = case_when(
    week %in% c(9, 10, 11, 12, 13, 14) ~ "early", 
    week %in% c(15, 16, 17, 18, 19, 20, 21) ~ "late"
  )) 

rwc_leaves_y0_df <- rwc_df %>% 
  filter(type == "leaf", 
         year %in% c(0, "NA")) %>% 
  group_by(tree, date) %>% 
  mutate(mean_swc_per_dry_g = mean(swc_per_dry_g)
         , mean_swc_g = mean(swc_g)) %>% 
  mutate(date_rwc = date, 
         week = as.numeric(week)) %>% 
  select(-date) %>% 
  distinct() %>% 
  select(mean_swc_per_dry_g, mean_swc_g, tree, week, date_rwc, rep) %>% 
  as.data.frame()

 wc_rwc_df <- merge(wc_df, rwc_leaves_y0, 
                    by = c("tree", "week", "rep"), 
                    all = T) 
 
 
 wp_wc_rwc_df <- merge(wp_df, wc_rwc_df, 
                       by = c("tree", "week", "rep", "timing"), 
                       all = T) %>% 
   select(-mpa, -date) #not sure why thats there
 
```


```{r}
#setDT(wc_rwc_df)[, lapply(.SD, na.omit), by = c(tree, date)]
#%>% 
#   mutate(mean_pd = mean(mpa_pd), 
#          mean_md = mean(mpa_md), 
#          mean_pd_lwc_leaf = mean(l))
 
 wp_wc_rwc_summary_df <- wp_wc_rwc_df %>% 
   group_by(week, tree) %>% 
   summarise(mean_md = mean(mpa_md), 
             mean_pd = mean(mpa_pd), 
             mean_lwc_md_bulk = mean(lwc_md_bulk), 
             mean_lwc_pd_bulk = mean(lwc_pd_bulk), 
             mean_swc_g = mean(mean_swc_g), 
             mean_swc_per_dry_g = mean(mean_swc_per_dry_g))
```

```{r}
wp_wc_rwc_summary_df %>% 
  ggplot(aes(y = mean_swc_per_dry_g, x = mean_md, color = as.factor(tree))) +
  geom_point()
```


