---
title: "ks_processing_IB"
author: "Indra Boving"
date: "5/21/2022"
output: html_document
---

```{r setup, include=FALSE}
library(janitor)
library(here)
library(tidyverse)
library(lubridate)
library(readxl)
```

Read in data: 
```{r}
ks_data <- read_csv(here("data", "ks_data", "ks_alldates.csv")) %>% 
  clean_names() %>% 
  mutate(date = lubridate::mdy(date)) %>% 
  mutate(week = week(date)) %>% 
 # mutate(tree = as.factor(tree)) %>% 
  mutate(alas = total_area/sapwood_area) 

dlookr::diagnose(ks_data)

unique(ks_data$date)


unique(ks_data$week)
```

Read in water potential data: 
- We measured Ks on stems collected on "2022-04-25" "2022-03-27" "2022-04-12" and "2022-05-23"
```{r}
####### Water Potentials 
#Date: 228 WP + LWC
wpwc228 <- read_excel(here("Data_05302022","WP_WC", "SHIFT data collection 2022.xlsx"), sheet="228 WP + LWC", skip=5, na = "NA") %>% clean_names()

#Date: 38-311 WP + LWC
wpwc38 <-  read_excel(here("Data_05302022","WP_WC", "SHIFT data collection 2022.xlsx"), sheet="38-311 WP + LWC", skip=5, na = "NA") %>% clean_names()
# remove mislabeled tree 2567 which was actually 2367 
wpwc38 <- wpwc38[-which(wpwc38$tag=="2567"),]

#Date: 315 WP + LWC
wpwc315 <- read_excel(here("Data_05302022","WP_WC", "SHIFT data collection 2022.xlsx"), sheet="315 WP + LWC", skip=5, na = "NA") %>% clean_names()

#Date: 325 WP + LWC
wpwc325 <- read_excel(here("Data_05302022","WP_WC", "SHIFT data collection 2022.xlsx"), sheet="325 WP + LWC", skip=5, na = "NA") %>% clean_names()

#Date: 330 WP + LWC (core)
wpwc330 <- read_excel(here("Data_05302022","WP_WC", "SHIFT data collection 2022.xlsx"), sheet="330 WP + LWC", skip=5, na = "NA") %>% clean_names()

#Date: 411-412 WP + LWC (satellite)
wpwc44 <- read_excel(here("Data_05302022","WP_WC", "SHIFT data collection 2022.xlsx"), sheet="44 WP + LWC", skip=5, na = "NA") %>% clean_names()

#Date: 411-412 WP + LWC
wpwc411 <-read_excel(here("Data_05302022","WP_WC", "SHIFT data collection 2022.xlsx"), sheet="411-412 WP + LWC", skip=5, na = "NA") %>% clean_names()

#Date: 411-412 WP + LWC
wpwc413 <-read_excel(here("Data_05302022","WP_WC", "SHIFT data collection 2022.xlsx"), sheet="413-414 WP + LWC", skip=5, na = "NA") %>% clean_names()

#Date: 425 WP + LWC
wpwc425 <-read_excel(here("Data_05302022","WP_WC", "SHIFT data collection 2022.xlsx"), sheet="425 WP + LWC", skip=5, na = "NA") %>% clean_names()

#Date: 427 WP + LWC
wpwc427 <-read_excel(here("Data_05302022","WP_WC", "SHIFT data collection 2022.xlsx"), sheet="427 WP + LWC", skip=5, na = "NA") %>% clean_names()

#Date: 523-525 WP + LWC
wpwc523 <-read_excel(here("Data_05302022","WP_WC", "SHIFT data collection 2022.xlsx"), sheet="523 WP + LWC", skip=5, na = "NA") %>% clean_names()

wpwc525 <-read_excel(here("Data_05302022","WP_WC", "SHIFT data collection 2022.xlsx"), sheet="525 WP + LWC", skip=5, na = "NA") %>% clean_names()
```

```{r}
wp315md <- wpwc315 %>%
  as.data.frame() %>% 
  filter(!is.na(tag)) %>%
  dplyr::select(!matches("_g_")) %>% 
  dplyr::select(1:3,matches("md")) %>% 
  dplyr::select(-md_bulk_wet, -md_bulk_dry, -md_avg) %>% 
  pivot_longer(cols=matches("md[1-9]") 
               , names_to="md"
               , values_to="mpa"
               , values_drop_na=TRUE) %>% 
  mutate(date = mdy("03-15-2022"))

#For 3.25
wp325md <- wpwc325 %>%
  as.data.frame() %>% 
  filter(!is.na(tag)) %>%
  dplyr::select(!matches("_g_")) %>% 
  dplyr::select(1:3,matches("md")) %>% 
  dplyr::select(-md_bulk_wet, -md_bulk_dry, -md_avg) %>% 
  pivot_longer(cols=matches("md[1-9]") 
               , names_to="md"
               , values_to="mpa"
               , values_drop_na=TRUE) %>% 
  mutate(date = mdy("03-25-2022"))

#For 3.30
wp330md <- wpwc330 %>%
  as.data.frame() %>% 
  filter(!is.na(tag)) %>%
  dplyr::select(!matches("_g_")) %>% 
  dplyr::select(1:3,matches("md")) %>% 
  dplyr::select(-md_bulk_wet, -md_bulk_dry, -md_avg) %>% 
  pivot_longer(cols=matches("md[1-9]") 
               , names_to="md"
               , values_to="mpa"
               , values_drop_na=TRUE) %>% 
  mutate(date = mdy("03-30-2022")) 

#For 4.11
wp411md <- wpwc411 %>%
  as.data.frame() %>% 
  filter(!is.na(tag)) %>%
  dplyr::select(!matches("_g_")) %>% 
  dplyr::select(1:3,matches("md")) %>% 
  dplyr::select(-md_bulk_wet, -md_bulk_dry, -md_avg) %>% 
  pivot_longer(cols=matches("md[1-9]") 
               , names_to="md"
               , values_to="mpa"
               , values_drop_na=TRUE) %>% 
  mutate(date = mdy("04-11-2022"))


#For 4.13
wp413md <- wpwc413 %>%
  as.data.frame() %>% 
  filter(!is.na(tag)) %>%
  dplyr::select(!matches("_g_")) %>% 
  dplyr::select(1:3,matches("md")) %>% 
  dplyr::select(-md_bulk_wet, -md_bulk_dry, -md_avg) %>% 
  pivot_longer(cols=matches("md[1-9]") 
               , names_to="md"
               , values_to="mpa"
               , values_drop_na=TRUE) %>% 
  mutate(date = mdy("04-13-2022"))

#For 4.25
wp425md <- wpwc425 %>%
  as.data.frame() %>% 
  filter(!is.na(tag)) %>%
  dplyr::select(!matches("_g_")) %>% 
  dplyr::select(1:3,matches("md")) %>% 
  dplyr::select(-md_bulk_wet, -md_bulk_dry, -md_avg) %>% 
  mutate(md1 = as.numeric(md1)) %>% 
  pivot_longer(cols=matches("md[1-9]") 
               , names_to="md"
               , values_to="mpa"
               , values_drop_na=TRUE) %>% 
  mutate(date = mdy("04-25-2022"))

wp523md <- wpwc523 %>%
  as.data.frame() %>% 
  filter(!is.na(tag)) %>%
  dplyr::select(!matches("_g_")) %>% 
  dplyr::select(1:3,matches("md")) %>% 
  dplyr::select(-md_bulk_wet, -md_bulk_dry, -md_avg) %>% 
  pivot_longer(cols=matches("md[1-9]") 
               , names_to="md"
               , values_to="mpa"
               , values_drop_na=TRUE) %>% 
  mutate(date = mdy("05-23-2022"))


###
###Combine all together: 
###

wp_alldates_md <- rbind(wp523md, wp411md, wp325md, wp330md, wp315md, wp425md, wp413md) %>% 
  mutate(week = week(date)) %>% 
  mutate(tree = as.numeric(tag)) 

wp_alldates_md_summary <- wp_alldates_md %>% 
  group_by(date, tag) %>% 
  mutate(mean_md = mean(mpa)) %>% 
  mutate(week_real = week) %>% 
  mutate(week = case_when(
    week == 12 ~ 13, 
    TRUE ~ as.numeric(week))) %>% 
  ungroup() %>% 
  dplyr::select(-date, -plot_number, -species, -md)
```
Combine WP data into Ks dataset: 
```{r}
ks_data_wp <- merge(ks_data, wp_alldates_md_summary, by = c("tree", "week")) %>% 
  mutate(tree = as.factor(tree)) %>% 
  mutate(date = date)
```


Look at it!
```{r}
ks_data_wp %>% 
  ggplot(aes(y = mpa, x = date, color = tree)) +
  geom_point() + 
  stat_summary(fun.y="mean", geom="line", aes(group=factor(tree))) 
```

```{r}
ks_data_wp %>% 
ggplot(aes(y = ks_g_s_mm_m_pa_nat, x = mpa, color = tree)) +
  geom_point() + 
  geom_smooth(method = "lm", se = F)
  ggtitle("Kleaf over time")
```

```{r}
ks_data_wp %>% 
ggplot(aes(y = kl_g_s_mm_m_pa_nat, x = date, color = tree)) +
  geom_point() + 
  stat_summary(fun.y="mean", geom="line", aes(group=factor(tree))) +
  ggtitle("Kleaf over time")
```

```{r}
ks_data %>% 
ggplot(aes(y = ks_g_s_mm_m_pa_nat, x = date, color = tree)) +
  geom_point()+ 
  stat_summary(fun.y="mean", geom="line", aes(group=factor(tree))) +
  ggtitle("Kstem over time")
```

```{r}
ks_data %>% 
  filter(plc > 0) %>% 
ggplot(aes(y = plc, x = date, color = tree)) +
  geom_point()+ 
  stat_summary(fun.y="mean", geom="line", aes(group=factor(tree))) +
  ggtitle("PLC over time")
```

```{r}
ks_data %>% 
  filter(plc > 0) %>% 
ggplot(aes(y = k_g_mm_s_m_pa_max, x = date, color = tree)) +
  geom_point()+ 
  stat_summary(fun.y="mean", geom="line", aes(group=factor(tree))) +
  ggtitle("Max flow over time")
```
```{r}
ks_data %>% 
  filter(plc > 0) %>% 
ggplot(aes(y = k_g_mm_s_m_pa_max, x = mpa, color = tree)) +
  geom_point()+ 
  stat_summary(fun.y="mean", geom="line", aes(group=factor(tree))) +
  ggtitle("Max flow over time")
```

```{r}
ks_data %>% 
  filter(plc > 0) %>% 
ggplot(aes(y = log(alas), x = k_g_mm_s_m_pa_nat, color = tree)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)
```

```{r}
ks_data %>% 
  filter(plc > 0) %>% 
ggplot(aes(y = alas, x = k_g_mm_s_m_pa_nat, color = tree)) +
  geom_smooth(method = "lm", se = F) +
  geom_point() 
```